--
-- 003_form_schema.sql
--
-- Extends the schema so a single view `vw_form_fields` exposes columns that
-- match database_fields.txt exactly. Underlying tables remain normalized; the
-- view flattens to a denormalized shape for CData / app consumption.

-- 1) Patients: add demographic, identifiers, contact, history, misc
ALTER TABLE public.patients
  ADD COLUMN IF NOT EXISTS middle_name TEXT,
  ADD COLUMN IF NOT EXISTS full_name TEXT,
  ADD COLUMN IF NOT EXISTS sex_at_birth TEXT,
  ADD COLUMN IF NOT EXISTS gender_identity TEXT,
  ADD COLUMN IF NOT EXISTS ssn_last_4 TEXT,
  ADD COLUMN IF NOT EXISTS marital_status TEXT,
  ADD COLUMN IF NOT EXISTS preferred_language TEXT,
  ADD COLUMN IF NOT EXISTS race TEXT,
  ADD COLUMN IF NOT EXISTS ethnicity TEXT,
  ADD COLUMN IF NOT EXISTS email_address TEXT,
  ADD COLUMN IF NOT EXISTS mobile_phone TEXT,
  ADD COLUMN IF NOT EXISTS home_phone TEXT,
  ADD COLUMN IF NOT EXISTS preferred_contact_method TEXT,
  ADD COLUMN IF NOT EXISTS address_line_2 TEXT,
  ADD COLUMN IF NOT EXISTS country TEXT,
  ADD COLUMN IF NOT EXISTS enterprise_patient_id TEXT,
  ADD COLUMN IF NOT EXISTS external_mrn TEXT,
  ADD COLUMN IF NOT EXISTS barcode_id TEXT,
  ADD COLUMN IF NOT EXISTS passport_number TEXT,
  ADD COLUMN IF NOT EXISTS driver_license_number TEXT,
  ADD COLUMN IF NOT EXISTS allergies_text TEXT,
  ADD COLUMN IF NOT EXISTS smoking_status TEXT,
  ADD COLUMN IF NOT EXISTS alcohol_use TEXT,
  ADD COLUMN IF NOT EXISTS pregnancy_status TEXT,
  ADD COLUMN IF NOT EXISTS chronic_conditions TEXT,
  ADD COLUMN IF NOT EXISTS past_surgical_history TEXT,
  ADD COLUMN IF NOT EXISTS family_history TEXT,
  ADD COLUMN IF NOT EXISTS preferred_pharmacy_name TEXT,
  ADD COLUMN IF NOT EXISTS preferred_pharmacy_phone TEXT,
  ADD COLUMN IF NOT EXISTS pharmacy_ncpdp TEXT,
  ADD COLUMN IF NOT EXISTS guardian_name TEXT,
  ADD COLUMN IF NOT EXISTS guarantor_name TEXT,
  ADD COLUMN IF NOT EXISTS guarantor_relationship TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_relationship TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_email TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS current_medications TEXT,
  ADD COLUMN IF NOT EXISTS has_allergies BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_drug_use BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_alcohol_use BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_tobacco_use BOOLEAN,
  ADD COLUMN IF NOT EXISTS is_pregnant BOOLEAN,
  ADD COLUMN IF NOT EXISTS takes_medications BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_chronic_conditions BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_past_surgical_history BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_family_history BOOLEAN,
  ADD COLUMN IF NOT EXISTS work_phone TEXT,
  ADD COLUMN IF NOT EXISTS employer_name TEXT,
  ADD COLUMN IF NOT EXISTS employer_phone TEXT,
  ADD COLUMN IF NOT EXISTS employer_street_address TEXT,
  ADD COLUMN IF NOT EXISTS employer_city TEXT,
  ADD COLUMN IF NOT EXISTS employer_state TEXT,
  ADD COLUMN IF NOT EXISTS employer_postal_code TEXT,
  ADD COLUMN IF NOT EXISTS spouse_partner_parent_name TEXT,
  ADD COLUMN IF NOT EXISTS referral_source TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party_name TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party_street_address TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party_city TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party_state TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party_postal_code TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party_phone TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party_email TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party_birthdate DATE,
  ADD COLUMN IF NOT EXISTS former_dentist_name TEXT,
  ADD COLUMN IF NOT EXISTS former_dentist_phone TEXT,
  ADD COLUMN IF NOT EXISTS last_dental_visit_date DATE,
  ADD COLUMN IF NOT EXISTS last_dental_xray_date DATE,
  ADD COLUMN IF NOT EXISTS floss_frequency TEXT,
  ADD COLUMN IF NOT EXISTS brush_frequency TEXT,
  ADD COLUMN IF NOT EXISTS physician_last_visit_date DATE,
  ADD COLUMN IF NOT EXISTS fen_phen_use BOOLEAN,
  ADD COLUMN IF NOT EXISTS serious_illness_or_operations BOOLEAN,
  ADD COLUMN IF NOT EXISTS serious_illness_description TEXT,
  ADD COLUMN IF NOT EXISTS blood_transfusion BOOLEAN,
  ADD COLUMN IF NOT EXISTS blood_transfusion_dates TEXT,
  ADD COLUMN IF NOT EXISTS nursing BOOLEAN,
  ADD COLUMN IF NOT EXISTS birth_control_use BOOLEAN,
  ADD COLUMN IF NOT EXISTS medications_with_diagnoses TEXT,
  ADD COLUMN IF NOT EXISTS allergy_1 TEXT,
  ADD COLUMN IF NOT EXISTS allergy_2 TEXT,
  ADD COLUMN IF NOT EXISTS patient_guardian_signature TEXT,
  ADD COLUMN IF NOT EXISTS patient_guardian_signature_date DATE,
  ADD COLUMN IF NOT EXISTS dental_problem_bad_breath BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_loose_teeth_or_broken_fillings BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_bleeding_gums BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_periodontal_treatment BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_clicking_popping_jaw BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_sensitivity_cold_hot_sweets BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_food_collection_between_teeth BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_sensitivity_when_biting BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_grinding_teeth BOOLEAN,
  ADD COLUMN IF NOT EXISTS dental_problem_sores_or_growth_in_mouth BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_anemia BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_fainting BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_radiation_treatment BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_arthritis_rheumatism BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_glaucoma BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_respiratory_disease BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_artificial_heart_valves BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_headaches BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_rheumatic_fever BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_artificial_joints BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_heart_murmur BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_scarlet_fever BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_asthma BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_heart_problems BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_sexually_transmitted_disease BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_bleeding_abnormally BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_hemophilia BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_stroke BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_blood_disease BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_hepatitis BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_swelling_feet_ankles BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_cancer BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_high_blood_pressure BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_thyroid_problems BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_chemical_dependency BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_hiv_aids BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_tobacco_use BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_chemotherapy BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_jaw_pain BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_tonsillitis BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_circulatory_problems BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_kidney_disease BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_tuberculosis BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_congenital_heart_lesions BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_liver_disease BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_ulcer BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_diabetes BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_mitral_valve_prolapse BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_epilepsy BOOLEAN,
  ADD COLUMN IF NOT EXISTS medical_history_pacemaker BOOLEAN;

-- Backfill full_name for existing rows (first [middle] last)
UPDATE public.patients
SET full_name = CONCAT_WS(' ', first_name, NULLIF(middle_name, ''), last_name)
WHERE (full_name IS NULL OR full_name = '');

-- 2) Encounters: add visit, providers, facility, scheduling
ALTER TABLE public.encounters
  ADD COLUMN IF NOT EXISTS visit_number TEXT,
  ADD COLUMN IF NOT EXISTS reason_for_visit TEXT,
  ADD COLUMN IF NOT EXISTS triage_level TEXT,
  ADD COLUMN IF NOT EXISTS discharge_disposition TEXT,
  ADD COLUMN IF NOT EXISTS visit_status TEXT,
  ADD COLUMN IF NOT EXISTS attending_provider_name TEXT,
  ADD COLUMN IF NOT EXISTS attending_provider_npi TEXT,
  ADD COLUMN IF NOT EXISTS ordering_provider_name TEXT,
  ADD COLUMN IF NOT EXISTS ordering_provider_npi TEXT,
  ADD COLUMN IF NOT EXISTS referring_provider_name TEXT,
  ADD COLUMN IF NOT EXISTS referring_provider_npi TEXT,
  ADD COLUMN IF NOT EXISTS primary_care_provider TEXT,
  ADD COLUMN IF NOT EXISTS rendering_provider_npi TEXT,
  ADD COLUMN IF NOT EXISTS facility_name TEXT,
  ADD COLUMN IF NOT EXISTS facility_npi TEXT,
  ADD COLUMN IF NOT EXISTS facility_address TEXT,
  ADD COLUMN IF NOT EXISTS appointment_id TEXT,
  ADD COLUMN IF NOT EXISTS appointment_date DATE,
  ADD COLUMN IF NOT EXISTS appointment_time TIME,
  ADD COLUMN IF NOT EXISTS check_in_time TIME,
  ADD COLUMN IF NOT EXISTS check_out_time TIME,
  ADD COLUMN IF NOT EXISTS no_show_flag BOOLEAN,
  ADD COLUMN IF NOT EXISTS rescheduled_flag BOOLEAN;

-- 3) Insurance summary (primary/secondary)
CREATE TABLE IF NOT EXISTS public.insurance_summary (
  patient_id INTEGER PRIMARY KEY REFERENCES public.patients(id) ON DELETE CASCADE,
  primary_insurance_payer TEXT,
  primary_member_id TEXT,
  primary_group_number TEXT,
  primary_plan_name TEXT,
  secondary_insurance_payer TEXT,
  secondary_member_id TEXT,
  secondary_group_number TEXT,
  coverage_start_date DATE,
  coverage_end_date DATE,
  copay_amount NUMERIC(10,2),
  coinsurance_percentage NUMERIC(5,2),
  deductible_remaining NUMERIC(12,2),
  prior_auth_number TEXT,
  referral_required BOOLEAN
);

ALTER TABLE public.insurance_summary
  ADD COLUMN IF NOT EXISTS primary_insurance_phone TEXT,
  ADD COLUMN IF NOT EXISTS primary_insurance_address TEXT,
  ADD COLUMN IF NOT EXISTS primary_insurance_city TEXT,
  ADD COLUMN IF NOT EXISTS primary_insurance_state TEXT,
  ADD COLUMN IF NOT EXISTS primary_insurance_postal_code TEXT,
  ADD COLUMN IF NOT EXISTS primary_subscriber_ssn TEXT,
  ADD COLUMN IF NOT EXISTS primary_deductible_amount NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS primary_deductible_used NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS primary_annual_max_benefit NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS primary_subscriber_name TEXT,
  ADD COLUMN IF NOT EXISTS primary_employer_name TEXT,
  ADD COLUMN IF NOT EXISTS primary_employer_phone TEXT,
  ADD COLUMN IF NOT EXISTS primary_employer_address TEXT,
  ADD COLUMN IF NOT EXISTS primary_employer_city TEXT,
  ADD COLUMN IF NOT EXISTS primary_employer_state TEXT,
  ADD COLUMN IF NOT EXISTS primary_employer_postal_code TEXT,
  ADD COLUMN IF NOT EXISTS secondary_insurance_phone TEXT,
  ADD COLUMN IF NOT EXISTS secondary_insurance_address TEXT,
  ADD COLUMN IF NOT EXISTS secondary_insurance_city TEXT,
  ADD COLUMN IF NOT EXISTS secondary_insurance_state TEXT,
  ADD COLUMN IF NOT EXISTS secondary_insurance_postal_code TEXT,
  ADD COLUMN IF NOT EXISTS secondary_subscriber_ssn TEXT,
  ADD COLUMN IF NOT EXISTS secondary_deductible_amount NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS secondary_deductible_used NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS secondary_annual_max_benefit NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS secondary_subscriber_name TEXT,
  ADD COLUMN IF NOT EXISTS secondary_employer_name TEXT,
  ADD COLUMN IF NOT EXISTS secondary_employer_phone TEXT,
  ADD COLUMN IF NOT EXISTS secondary_employer_address TEXT,
  ADD COLUMN IF NOT EXISTS secondary_employer_city TEXT,
  ADD COLUMN IF NOT EXISTS secondary_employer_state TEXT,
  ADD COLUMN IF NOT EXISTS secondary_employer_postal_code TEXT;

-- 4) Vitals per-encounter
CREATE TABLE IF NOT EXISTS public.vitals (
  id SERIAL PRIMARY KEY,
  encounter_id INTEGER NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  height_cm NUMERIC(6,2),
  weight_kg NUMERIC(6,2),
  bmi NUMERIC(6,2),
  temperature_c NUMERIC(5,2),
  heart_rate_bpm INTEGER,
  respiratory_rate INTEGER,
  oxygen_saturation NUMERIC(5,2),
  blood_pressure_systolic INTEGER,
  blood_pressure_diastolic INTEGER,
  recorded_at TIMESTAMP DEFAULT NOW()
);

-- 5) Medications (latest)
CREATE TABLE IF NOT EXISTS public.medications (
  id SERIAL PRIMARY KEY,
  encounter_id INTEGER NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  medication_name TEXT,
  medication_dose_mg NUMERIC(10,2),
  medication_route TEXT,
  medication_frequency TEXT,
  recorded_at TIMESTAMP DEFAULT NOW()
);

-- 6) Labs (latest)
CREATE TABLE IF NOT EXISTS public.labs (
  id SERIAL PRIMARY KEY,
  encounter_id INTEGER NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  lab_order_id TEXT UNIQUE,
  lab_order_datetime TIMESTAMP,
  lab_test_name TEXT,
  lab_loinc_code TEXT,
  lab_result_value TEXT,
  lab_result_units TEXT,
  lab_result_flag TEXT,
  lab_collected_datetime TIMESTAMP,
  lab_reported_datetime TIMESTAMP
);

-- 7) Imaging (latest)
CREATE TABLE IF NOT EXISTS public.imaging (
  id SERIAL PRIMARY KEY,
  encounter_id INTEGER NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  imaging_order_id TEXT,
  imaging_modality TEXT,
  imaging_body_part TEXT,
  radiology_report_impression TEXT,
  radiology_report_datetime TIMESTAMP
);

-- 8) Diagnoses and Procedures
CREATE TABLE IF NOT EXISTS public.diagnoses (
  id SERIAL PRIMARY KEY,
  encounter_id INTEGER NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  primary_diagnosis_code TEXT,
  primary_diagnosis_description TEXT,
  secondary_diagnosis_code TEXT,
  secondary_diagnosis_description TEXT,
  icd10_code_1 TEXT,
  icd10_code_2 TEXT
);

CREATE TABLE IF NOT EXISTS public.procedures (
  id SERIAL PRIMARY KEY,
  encounter_id INTEGER NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  cpt_code_1 TEXT,
  cpt_code_2 TEXT,
  procedure_datetime TIMESTAMP,
  anesthesia_minutes INTEGER
);

-- 9) Claims / Billing
CREATE TABLE IF NOT EXISTS public.claims (
  id SERIAL PRIMARY KEY,
  encounter_id INTEGER NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  claim_number TEXT,
  claim_status TEXT,
  claim_submitted_date DATE,
  claim_paid_date DATE,
  total_charges NUMERIC(12,2),
  patient_responsibility NUMERIC(12,2),
  balance_due NUMERIC(12,2),
  payment_plan_active BOOLEAN,
  eob_date DATE,
  billing_notes TEXT
);

-- 10) Consents
CREATE TABLE IF NOT EXISTS public.consents (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER UNIQUE NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  consent_for_treatment_signed BOOLEAN,
  hipaa_acknowledgement_date DATE,
  privacy_notice_signed BOOLEAN,
  assignment_of_benefits_signed BOOLEAN,
  telehealth_consent_signed BOOLEAN
);

-- Seed/updates for sample patient MRN100001
UPDATE public.patients SET
  middle_name = 'L',
  sex_at_birth = 'Female',
  gender_identity = 'Female',
  ssn_last_4 = '1234',
  marital_status = 'Single',
  preferred_language = 'English',
  race = 'Asian',
  ethnicity = 'Not Hispanic or Latino',
  email_address = 'ava.nguyen@example.com',
  mobile_phone = '555-123-4567',
  home_phone = '555-321-7654',
  preferred_contact_method = 'mobile_phone',
  address_line_2 = 'Apt 2B',
  country = 'USA',
  enterprise_patient_id = 'EID-0001',
  external_mrn = 'EXT-MRN-0001',
  barcode_id = 'BR-1001',
  passport_number = 'X12345678',
  driver_license_number = 'NYS-NG1234567',
  allergies_text = 'Penicillin',
  smoking_status = 'Never',
  alcohol_use = 'Occasional',
  pregnancy_status = 'N/A',
  chronic_conditions = 'Hypertension',
  past_surgical_history = 'Appendectomy (2010)',
  family_history = 'Father: diabetes',
  preferred_pharmacy_name = 'Acme Pharmacy',
  preferred_pharmacy_phone = '555-888-9900',
  pharmacy_ncpdp = '1234567',
  guardian_name = 'Lan Nguyen',
  guarantor_name = 'L Nguyen',
  guarantor_relationship = 'Parent',
  emergency_contact_name = 'Minh Nguyen',
  emergency_contact_relationship = 'Father',
  emergency_contact_phone = '555-222-3333',
  emergency_contact_email = 'minh.nguyen@example.com',
  notes = 'Prefers morning appointments',
  current_medications = 'Lisinopril 10mg daily',
  has_allergies = true,
  has_drug_use = false,
  has_alcohol_use = true,
  has_tobacco_use = false,
  is_pregnant = false,
  takes_medications = true,
  has_chronic_conditions = true,
  has_past_surgical_history = true,
  has_family_history = true,
  work_phone = '555-555-9012',
  employer_name = 'Albany Community College',
  employer_phone = '555-555-9012',
  employer_street_address = '200 Market St',
  employer_city = 'Albany',
  employer_state = 'NY',
  employer_postal_code = '12207',
  spouse_partner_parent_name = 'Minh Nguyen',
  referral_source = 'Friend referral',
  responsible_party_name = 'L Nguyen',
  responsible_party_street_address = '10 Pine St',
  responsible_party_city = 'Albany',
  responsible_party_state = 'NY',
  responsible_party_postal_code = '12207',
  responsible_party_phone = '555-222-3333',
  responsible_party_email = 'l.nguyen@example.com',
  responsible_party_birthdate = '1965-03-15',
  former_dentist_name = 'Dr. Howard Lee',
  former_dentist_phone = '555-777-1212',
  last_dental_visit_date = '2024-06-15',
  last_dental_xray_date = '2023-11-10',
  floss_frequency = 'Daily',
  brush_frequency = 'Twice daily',
  physician_last_visit_date = '2024-08-20',
  fen_phen_use = false,
  serious_illness_or_operations = true,
  serious_illness_description = 'Appendectomy (2010)',
  blood_transfusion = false,
  blood_transfusion_dates = 'N/A',
  nursing = false,
  birth_control_use = false,
  medications_with_diagnoses = 'Lisinopril - Hypertension',
  allergy_1 = 'Penicillin',
  allergy_2 = 'Seasonal pollen',
  patient_guardian_signature = 'Ava Nguyen',
  patient_guardian_signature_date = '2025-12-20',
  dental_problem_bad_breath = false,
  dental_problem_loose_teeth_or_broken_fillings = false,
  dental_problem_bleeding_gums = true,
  dental_problem_periodontal_treatment = false,
  dental_problem_clicking_popping_jaw = false,
  dental_problem_sensitivity_cold_hot_sweets = true,
  dental_problem_food_collection_between_teeth = false,
  dental_problem_sensitivity_when_biting = false,
  dental_problem_grinding_teeth = true,
  dental_problem_sores_or_growth_in_mouth = false,
  medical_history_anemia = false,
  medical_history_fainting = false,
  medical_history_radiation_treatment = false,
  medical_history_arthritis_rheumatism = false,
  medical_history_glaucoma = false,
  medical_history_respiratory_disease = false,
  medical_history_artificial_heart_valves = false,
  medical_history_headaches = true,
  medical_history_rheumatic_fever = false,
  medical_history_artificial_joints = false,
  medical_history_heart_murmur = false,
  medical_history_scarlet_fever = false,
  medical_history_asthma = false,
  medical_history_heart_problems = false,
  medical_history_sexually_transmitted_disease = false,
  medical_history_bleeding_abnormally = false,
  medical_history_hemophilia = false,
  medical_history_stroke = false,
  medical_history_blood_disease = false,
  medical_history_hepatitis = false,
  medical_history_swelling_feet_ankles = false,
  medical_history_cancer = false,
  medical_history_high_blood_pressure = true,
  medical_history_thyroid_problems = false,
  medical_history_chemical_dependency = false,
  medical_history_hiv_aids = false,
  medical_history_tobacco_use = false,
  medical_history_chemotherapy = false,
  medical_history_jaw_pain = false,
  medical_history_tonsillitis = false,
  medical_history_circulatory_problems = false,
  medical_history_kidney_disease = false,
  medical_history_tuberculosis = false,
  medical_history_congenital_heart_lesions = false,
  medical_history_liver_disease = false,
  medical_history_ulcer = false,
  medical_history_diabetes = true,
  medical_history_mitral_valve_prolapse = false,
  medical_history_epilepsy = false,
  medical_history_pacemaker = false
WHERE mrn = 'MRN100001';

-- Update encounters row for the same patient
UPDATE public.encounters e
SET visit_number = 'V-001',
    reason_for_visit = 'Follow-up',
    triage_level = '3',
    discharge_disposition = 'Home',
    visit_status = 'Closed',
    attending_provider_name = 'Dr. Julia Park',
    attending_provider_npi = '1234567890',
    ordering_provider_name = 'Dr. Julia Park',
    ordering_provider_npi = '1234567890',
    referring_provider_name = 'Dr. Sam Chen',
    referring_provider_npi = '0987654321',
    primary_care_provider = 'Dr. Alice Kim',
    rendering_provider_npi = '1122334455',
    facility_name = 'Downtown Clinic',
    facility_npi = '5566778899',
    facility_address = '100 Health Way, Albany, NY 12207',
    appointment_id = 'APT-1001',
    appointment_date = NOW()::date,
    appointment_time = '09:30',
    check_in_time = '09:20',
    check_out_time = '09:55',
    no_show_flag = false,
    rescheduled_flag = false
FROM public.patients p
WHERE e.patient_id = p.id AND p.mrn = 'MRN100001';

-- Seed vitals for that encounter
INSERT INTO public.vitals (encounter_id, height_cm, weight_kg, bmi, temperature_c, heart_rate_bpm, respiratory_rate, oxygen_saturation, blood_pressure_systolic, blood_pressure_diastolic)
SELECT e.id, 165.0, 62.0, 22.8, 36.8, 72, 16, 98.0, 118, 76
FROM public.encounters e JOIN public.patients p ON e.patient_id = p.id
WHERE p.mrn = 'MRN100001'
ON CONFLICT DO NOTHING;

-- Seed insurance summary
INSERT INTO public.insurance_summary (
  patient_id,
  primary_insurance_payer,
  primary_member_id,
  primary_group_number,
  primary_plan_name,
  secondary_insurance_payer,
  secondary_member_id,
  secondary_group_number,
  coverage_start_date,
  coverage_end_date,
  copay_amount,
  coinsurance_percentage,
  deductible_remaining,
  prior_auth_number,
  referral_required,
  primary_insurance_phone,
  primary_insurance_address,
  primary_insurance_city,
  primary_insurance_state,
  primary_insurance_postal_code,
  primary_subscriber_ssn,
  primary_deductible_amount,
  primary_deductible_used,
  primary_annual_max_benefit,
  primary_subscriber_name,
  primary_employer_name,
  primary_employer_phone,
  primary_employer_address,
  primary_employer_city,
  primary_employer_state,
  primary_employer_postal_code,
  secondary_insurance_phone,
  secondary_insurance_address,
  secondary_insurance_city,
  secondary_insurance_state,
  secondary_insurance_postal_code,
  secondary_subscriber_ssn,
  secondary_deductible_amount,
  secondary_deductible_used,
  secondary_annual_max_benefit,
  secondary_subscriber_name,
  secondary_employer_name,
  secondary_employer_phone,
  secondary_employer_address,
  secondary_employer_city,
  secondary_employer_state,
  secondary_employer_postal_code
)
SELECT
  p.id,
  'Acme Health',
  'M-MRN100001',
  'GRP-100',
  'PPO Standard',
  'Backup Health',
  'S-MRN100001',
  'GRP-200',
  NOW()::date - INTERVAL '365 days',
  NOW()::date + INTERVAL '365 days',
  25.00,
  20.00,
  500.00,
  'AUTH-123',
  false,
  '555-111-2222',
  '200 Insurance Ave',
  'Albany',
  'NY',
  '12207',
  '123-45-6789',
  1000.00,
  250.00,
  2000.00,
  'Ava Nguyen',
  'Albany Community College',
  '555-555-9012',
  '200 Market St',
  'Albany',
  'NY',
  '12207',
  '555-333-4444',
  '400 Backup St',
  'Albany',
  'NY',
  '12207',
  '987-65-4321',
  1500.00,
  100.00,
  1500.00,
  'L Nguyen',
  'State of NY',
  '555-666-7777',
  '1 Capitol Hill',
  'Albany',
  'NY',
  '12207'
FROM public.patients p WHERE p.mrn = 'MRN100001'
ON CONFLICT (patient_id) DO NOTHING;

-- Seed medication
INSERT INTO public.medications (encounter_id, medication_name, medication_dose_mg, medication_route, medication_frequency)
SELECT e.id, 'Lisinopril', 10, 'PO', 'daily'
FROM public.encounters e JOIN public.patients p ON e.patient_id = p.id
WHERE p.mrn = 'MRN100001'
ON CONFLICT DO NOTHING;

-- Seed a lab
INSERT INTO public.labs (encounter_id, lab_order_id, lab_order_datetime, lab_test_name, lab_loinc_code, lab_result_value, lab_result_units, lab_result_flag, lab_collected_datetime, lab_reported_datetime)
SELECT e.id, 'LAB-1001', NOW() - INTERVAL '1 day', 'Hemoglobin A1c', '4548-4', '5.6', '%', 'N', NOW() - INTERVAL '1 day', NOW() - INTERVAL '20 hours'
FROM public.encounters e JOIN public.patients p ON e.patient_id = p.id
WHERE p.mrn = 'MRN100001'
ON CONFLICT DO NOTHING;

-- Seed imaging
INSERT INTO public.imaging (encounter_id, imaging_order_id, imaging_modality, imaging_body_part, radiology_report_impression, radiology_report_datetime)
SELECT e.id, 'IMG-2001', 'XR', 'Chest', 'No acute cardiopulmonary disease.', NOW() - INTERVAL '1 day'
FROM public.encounters e JOIN public.patients p ON e.patient_id = p.id
WHERE p.mrn = 'MRN100001'
ON CONFLICT DO NOTHING;

-- Seed diagnoses and procedures
INSERT INTO public.diagnoses (encounter_id, primary_diagnosis_code, primary_diagnosis_description, secondary_diagnosis_code, secondary_diagnosis_description, icd10_code_1, icd10_code_2)
SELECT e.id, 'I10', 'Essential (primary) hypertension', 'E11.9', 'Type 2 diabetes mellitus without complications', 'I10', 'E11.9'
FROM public.encounters e JOIN public.patients p ON e.patient_id = p.id
WHERE p.mrn = 'MRN100001'
ON CONFLICT DO NOTHING;

INSERT INTO public.procedures (encounter_id, cpt_code_1, cpt_code_2, procedure_datetime, anesthesia_minutes)
SELECT e.id, '93000', '00100', NOW() - INTERVAL '2 days', 30
FROM public.encounters e JOIN public.patients p ON e.patient_id = p.id
WHERE p.mrn = 'MRN100001'
ON CONFLICT DO NOTHING;

-- Seed claims
INSERT INTO public.claims (encounter_id, claim_number, claim_status, claim_submitted_date, claim_paid_date, total_charges, patient_responsibility, balance_due, payment_plan_active, eob_date, billing_notes)
SELECT e.id, 'CLM-5001', 'Paid', (NOW() - INTERVAL '10 days')::date, (NOW() - INTERVAL '5 days')::date, 250.00, 50.00, 0.00, false, (NOW() - INTERVAL '5 days')::date, 'Processed successfully'
FROM public.encounters e JOIN public.patients p ON e.patient_id = p.id
WHERE p.mrn = 'MRN100001'
ON CONFLICT DO NOTHING;

-- Seed consents
INSERT INTO public.consents (patient_id, consent_for_treatment_signed, hipaa_acknowledgement_date, privacy_notice_signed, assignment_of_benefits_signed, telehealth_consent_signed)
SELECT p.id, true, (NOW() - INTERVAL '100 days')::date, true, true, true
FROM public.patients p WHERE p.mrn = 'MRN100001'
ON CONFLICT DO NOTHING;

-- 11) Denormalized view with columns matching database_fields.txt
CREATE OR REPLACE VIEW public.vw_form_fields AS
SELECT
  p.id AS patient_id,
  p.mrn,
  p.full_name,
  p.first_name,
  p.last_name,
  p.middle_name,
  p.dob AS date_of_birth,
  p.dob AS dob,
  -- Common aliases for mapping convenience
  COALESCE(p.email_address, NULL) AS email,
  COALESCE(p.mobile_phone, p.home_phone, p.phone) AS phone,
  p.postal_code AS zip,
  COALESCE(p.enterprise_patient_id, p.external_mrn, p.barcode_id) AS employee_id,
  NOW()::date AS date,
  p.sex_at_birth,
  p.gender_identity,
  p.ssn_last_4,
  p.marital_status,
  p.preferred_language,
  p.race,
  p.ethnicity,
  p.email_address,
  p.mobile_phone,
  p.home_phone,
  p.preferred_contact_method,
  p.street_address,
  p.address_line_2,
  p.city,
  p.state,
  p.postal_code,
  p.country,
  p.enterprise_patient_id,
  p.external_mrn,
  p.barcode_id,
  p.passport_number,
  p.driver_license_number,
  ins.primary_insurance_payer,
  ins.primary_member_id,
  ins.primary_group_number,
  ins.primary_plan_name,
  ins.secondary_insurance_payer,
  ins.secondary_member_id,
  ins.secondary_group_number,
  ins.coverage_start_date,
  ins.coverage_end_date,
  ins.copay_amount,
  ins.coinsurance_percentage,
  ins.deductible_remaining,
  ins.prior_auth_number,
  ins.referral_required,
  e.encounter_id,
  e.visit_number,
  e.admit_datetime,
  e.discharge_datetime,
  e.encounter_type,
  e.chief_complaint,
  e.reason_for_visit,
  e.triage_level,
  e.discharge_disposition,
  e.visit_status,
  e.attending_provider_name,
  e.attending_provider_npi,
  e.ordering_provider_name,
  e.ordering_provider_npi,
  e.referring_provider_name,
  e.referring_provider_npi,
  e.primary_care_provider,
  e.rendering_provider_npi,
  e.facility_name,
  e.facility_npi,
  e.facility_address,
  v.height_cm,
  v.weight_kg,
  v.bmi,
  v.temperature_c,
  v.heart_rate_bpm,
  v.respiratory_rate,
  v.oxygen_saturation,
  v.blood_pressure_systolic,
  v.blood_pressure_diastolic,
  p.allergies_text,
  p.has_allergies,
  p.has_drug_use,
  p.has_alcohol_use,
  p.has_tobacco_use,
  p.is_pregnant,
  p.takes_medications,
  p.has_chronic_conditions,
  p.has_past_surgical_history,
  p.has_family_history,
  p.smoking_status,
  p.alcohol_use,
  p.pregnancy_status,
  p.chronic_conditions,
  p.past_surgical_history,
  p.family_history,
  p.current_medications,
  m.medication_name,
  m.medication_dose_mg,
  m.medication_route,
  m.medication_frequency,
  m.recorded_at AS last_medication_update,
  l.lab_order_id,
  l.lab_order_datetime,
  l.lab_test_name,
  l.lab_loinc_code,
  l.lab_result_value,
  l.lab_result_units,
  l.lab_result_flag,
  l.lab_collected_datetime,
  l.lab_reported_datetime,
  i.imaging_order_id,
  i.imaging_modality,
  i.imaging_body_part,
  i.radiology_report_impression,
  i.radiology_report_datetime,
  d.primary_diagnosis_code,
  d.primary_diagnosis_description,
  d.secondary_diagnosis_code,
  d.secondary_diagnosis_description,
  d.icd10_code_1,
  d.icd10_code_2,
  pr.cpt_code_1,
  pr.cpt_code_2,
  pr.procedure_datetime,
  pr.anesthesia_minutes,
  c.claim_number,
  c.claim_status,
  c.claim_submitted_date,
  c.claim_paid_date,
  c.total_charges,
  c.patient_responsibility,
  c.balance_due,
  c.payment_plan_active,
  c.eob_date,
  c.billing_notes,
  con.consent_for_treatment_signed,
  con.hipaa_acknowledgement_date,
  con.privacy_notice_signed,
  con.assignment_of_benefits_signed,
  con.telehealth_consent_signed,
  p.emergency_contact_name,
  p.emergency_contact_relationship,
  p.emergency_contact_phone,
  p.emergency_contact_email,
  e.appointment_id,
  e.appointment_date,
  e.appointment_time,
  e.check_in_time,
  e.check_out_time,
  e.no_show_flag,
  e.rescheduled_flag,
  p.preferred_pharmacy_name,
  p.preferred_pharmacy_phone,
  p.pharmacy_ncpdp,
  p.guardian_name,
  p.guarantor_name,
  p.guarantor_relationship,
  p.notes,
  p.work_phone,
  p.employer_name,
  p.employer_phone,
  p.employer_street_address,
  p.employer_city,
  p.employer_state,
  p.employer_postal_code,
  p.spouse_partner_parent_name,
  p.referral_source,
  p.responsible_party_name,
  p.responsible_party_street_address,
  p.responsible_party_city,
  p.responsible_party_state,
  p.responsible_party_postal_code,
  p.responsible_party_phone,
  p.responsible_party_email,
  p.responsible_party_birthdate,
  p.former_dentist_name,
  p.former_dentist_phone,
  p.last_dental_visit_date,
  p.last_dental_xray_date,
  p.floss_frequency,
  p.brush_frequency,
  p.physician_last_visit_date,
  p.fen_phen_use,
  p.serious_illness_or_operations,
  p.serious_illness_description,
  p.blood_transfusion,
  p.blood_transfusion_dates,
  p.nursing,
  p.birth_control_use,
  p.medications_with_diagnoses,
  p.allergy_1,
  p.allergy_2,
  p.patient_guardian_signature,
  p.patient_guardian_signature_date,
  p.dental_problem_bad_breath,
  p.dental_problem_loose_teeth_or_broken_fillings,
  p.dental_problem_bleeding_gums,
  p.dental_problem_periodontal_treatment,
  p.dental_problem_clicking_popping_jaw,
  p.dental_problem_sensitivity_cold_hot_sweets,
  p.dental_problem_food_collection_between_teeth,
  p.dental_problem_sensitivity_when_biting,
  p.dental_problem_grinding_teeth,
  p.dental_problem_sores_or_growth_in_mouth,
  p.medical_history_anemia,
  p.medical_history_fainting,
  p.medical_history_radiation_treatment,
  p.medical_history_arthritis_rheumatism,
  p.medical_history_glaucoma,
  p.medical_history_respiratory_disease,
  p.medical_history_artificial_heart_valves,
  p.medical_history_headaches,
  p.medical_history_rheumatic_fever,
  p.medical_history_artificial_joints,
  p.medical_history_heart_murmur,
  p.medical_history_scarlet_fever,
  p.medical_history_asthma,
  p.medical_history_heart_problems,
  p.medical_history_sexually_transmitted_disease,
  p.medical_history_bleeding_abnormally,
  p.medical_history_hemophilia,
  p.medical_history_stroke,
  p.medical_history_blood_disease,
  p.medical_history_hepatitis,
  p.medical_history_swelling_feet_ankles,
  p.medical_history_cancer,
  p.medical_history_high_blood_pressure,
  p.medical_history_thyroid_problems,
  p.medical_history_chemical_dependency,
  p.medical_history_hiv_aids,
  p.medical_history_tobacco_use,
  p.medical_history_chemotherapy,
  p.medical_history_jaw_pain,
  p.medical_history_tonsillitis,
  p.medical_history_circulatory_problems,
  p.medical_history_kidney_disease,
  p.medical_history_tuberculosis,
  p.medical_history_congenital_heart_lesions,
  p.medical_history_liver_disease,
  p.medical_history_ulcer,
  p.medical_history_diabetes,
  p.medical_history_mitral_valve_prolapse,
  p.medical_history_epilepsy,
  p.medical_history_pacemaker,
  ins.primary_insurance_phone,
  ins.primary_insurance_address,
  ins.primary_insurance_city,
  ins.primary_insurance_state,
  ins.primary_insurance_postal_code,
  ins.primary_subscriber_ssn,
  ins.primary_deductible_amount,
  ins.primary_deductible_used,
  ins.primary_annual_max_benefit,
  ins.primary_subscriber_name,
  ins.primary_employer_name,
  ins.primary_employer_phone,
  ins.primary_employer_address,
  ins.primary_employer_city,
  ins.primary_employer_state,
  ins.primary_employer_postal_code,
  ins.secondary_insurance_phone,
  ins.secondary_insurance_address,
  ins.secondary_insurance_city,
  ins.secondary_insurance_state,
  ins.secondary_insurance_postal_code,
  ins.secondary_subscriber_ssn,
  ins.secondary_deductible_amount,
  ins.secondary_deductible_used,
  ins.secondary_annual_max_benefit,
  ins.secondary_subscriber_name,
  ins.secondary_employer_name,
  ins.secondary_employer_phone,
  ins.secondary_employer_address,
  ins.secondary_employer_city,
  ins.secondary_employer_state,
  ins.secondary_employer_postal_code
FROM public.patients p
LEFT JOIN public.insurance_summary ins ON ins.patient_id = p.id
LEFT JOIN public.encounters e ON e.patient_id = p.id
LEFT JOIN LATERAL (
  SELECT v.* FROM public.vitals v WHERE v.encounter_id = e.id ORDER BY v.recorded_at DESC NULLS LAST LIMIT 1
) v ON TRUE
LEFT JOIN LATERAL (
  SELECT m.* FROM public.medications m WHERE m.encounter_id = e.id ORDER BY m.recorded_at DESC NULLS LAST LIMIT 1
) m ON TRUE
LEFT JOIN LATERAL (
  SELECT l.* FROM public.labs l WHERE l.encounter_id = e.id ORDER BY l.lab_reported_datetime DESC NULLS LAST LIMIT 1
) l ON TRUE
LEFT JOIN LATERAL (
  SELECT i.* FROM public.imaging i WHERE i.encounter_id = e.id ORDER BY i.radiology_report_datetime DESC NULLS LAST LIMIT 1
) i ON TRUE
LEFT JOIN LATERAL (
  SELECT d.* FROM public.diagnoses d WHERE d.encounter_id = e.id ORDER BY d.id DESC LIMIT 1
) d ON TRUE
LEFT JOIN LATERAL (
  SELECT pr.* FROM public.procedures pr WHERE pr.encounter_id = e.id ORDER BY pr.procedure_datetime DESC NULLS LAST LIMIT 1
) pr ON TRUE
LEFT JOIN LATERAL (
  SELECT c.* FROM public.claims c WHERE c.encounter_id = e.id ORDER BY c.id DESC LIMIT 1
) c ON TRUE
LEFT JOIN public.consents con ON con.patient_id = p.id;
