"""Shared constants for detection job status."""

DETECTION_STATUS_QUEUED = "queued"
DETECTION_STATUS_RUNNING = "running"
DETECTION_STATUS_COMPLETE = "complete"
DETECTION_STATUS_FAILED = "failed"

DETECTION_TERMINAL_STATUSES = {DETECTION_STATUS_COMPLETE, DETECTION_STATUS_FAILED}
