// AUTO-GENERATED by scripts/build-form-catalog-index.mjs. Do not edit by hand.
// Run `node scripts/build-form-catalog-index.mjs` to refresh.

export const FORM_CATALOG_EXTERNAL_SOURCES = {
  "acord": {
    "key": "acord",
    "label": "ACORD (Insurance)",
    "sourceFile": "form_catalog/acord/links.txt",
    "links": [
      {
        "label": "ACORD forms library (canonical source, membership or subscription)",
        "url": "https://www.acord.org/standards-development/forms"
      },
      {
        "label": "ACORD standards development portal",
        "url": "https://www.acord.org/standards-development"
      },
      {
        "label": "ACORD membership + form access information",
        "url": "https://www.acord.org/membership"
      }
    ]
  },
  "contracts_procurement": {
    "key": "contracts_procurement",
    "label": "Contracts & Procurement",
    "sourceFile": "form_catalog/contracts_procurement/links.txt",
    "links": [
      {
        "label": "GSA forms index",
        "url": "https://www.gsa.gov/reference/forms"
      },
      {
        "label": "SF-18 - Request for Quotation",
        "url": "https://www.gsa.gov/system/files/SF18-95a.pdf"
      },
      {
        "label": "SF-24 - Bid Bond",
        "url": "https://www.gsa.gov/system/files/2024-02/SF24-23a.pdf"
      },
      {
        "label": "SF-25 - Performance Bond",
        "url": "https://www.gsa.gov/system/files/2024-02/SF25-23a.pdf"
      },
      {
        "label": "SF-25A - Payment Bond",
        "url": "https://www.gsa.gov/system/files/2024-02/SF25A-23a.pdf"
      },
      {
        "label": "SF-25B - Continuation Sheet (For Standard Forms 24, 25, and 25A)",
        "url": "https://www.gsa.gov/system/files/2024-02/SF25B-23a.pdf"
      },
      {
        "label": "SF-30 - Amendment of Solicitation/Modification of Contract",
        "url": "https://www.gsa.gov/system/files/SF30-16c.pdf"
      },
      {
        "label": "SF-1413 - Statement and Acknowledgment",
        "url": "https://www.gsa.gov/system/files/2025-05/SF1413-23a.pdf"
      },
      {
        "label": "SF-1414 - Consent of Surety",
        "url": "https://www.gsa.gov/system/files/2024-02/SF1414-23a.pdf"
      },
      {
        "label": "SF-1415 - Consent of Surety and Increase of Penalty",
        "url": "https://www.gsa.gov/system/files/2024-02/SF1415-23a.pdf"
      },
      {
        "label": "SF-1416 - Payment Bond for Other Than Construction Contracts",
        "url": "https://www.gsa.gov/system/files/2024-02/SF1416-23a.pdf"
      },
      {
        "label": "SF-1418 - Performance Bond for Other Than Construction Contracts",
        "url": "https://www.gsa.gov/system/files/2024-04/SF1418-23a.pdf"
      },
      {
        "label": "SF-1449 - Solicitation/Contract/Order for Commercial Products and Commercial Services",
        "url": "https://www.gsa.gov/system/files/SF1449-21.pdf"
      },
      {
        "label": "SF-3881 - ACH Vendor/Miscellaneous Payment Enrollment Form",
        "url": "https://www.gsa.gov/cdnstatic/SF3881-03b.pdf"
      },
      {
        "label": "SF-1199A - Direct Deposit Sign-Up Form",
        "url": "https://www.gsa.gov/cdnstatic/SF1199A-20.pdf"
      }
    ]
  },
  "criminal_justice": {
    "key": "criminal_justice",
    "label": "Federal Criminal",
    "sourceFile": "form_catalog/criminal_justice/links.txt",
    "links": [
      {
        "label": "U.S. Courts criminal forms index",
        "url": "https://www.uscourts.gov/forms-rules/forms/criminal-forms"
      },
      {
        "label": "AO 100A - Bail Information Sheet",
        "url": "https://www.uscourts.gov/sites/default/files/ao100a_0.pdf"
      },
      {
        "label": "AO 100B - Surety Information Sheet",
        "url": "https://www.uscourts.gov/sites/default/files/ao100b.pdf"
      },
      {
        "label": "AO 102 - Application for a Tracking Warrant",
        "url": "https://www.uscourts.gov/sites/default/files/ao102.pdf"
      },
      {
        "label": "AO 103 - Order Requiring Assistance in Executing a Tracking Warrant (Under Seal)",
        "url": "https://www.uscourts.gov/sites/default/files/ao103.pdf"
      },
      {
        "label": "AO 104 - Tracking Warrant",
        "url": "https://www.uscourts.gov/sites/default/files/ao104.pdf"
      },
      {
        "label": "AO 106 - Application for a Search Warrant",
        "url": "https://www.uscourts.gov/sites/default/files/ao106.pdf"
      },
      {
        "label": "AO 106A - Application for a Warrant by Telephone or Other Reliable Electronic Means",
        "url": "https://www.uscourts.gov/sites/default/files/ao_106a_0818_0.pdf"
      },
      {
        "label": "AO 108 - Application for a Warrant to Seize Property Subject to Forfeiture",
        "url": "https://www.uscourts.gov/sites/default/files/ao108.pdf"
      },
      {
        "label": "AO 109 - Warrant to Seize Property Subject to Forfeiture",
        "url": "https://www.uscourts.gov/sites/default/files/ao109.pdf"
      },
      {
        "label": "AO 110 - Subpoena to Testify Before Grand Jury",
        "url": "https://www.uscourts.gov/sites/default/files/ao110.pdf"
      },
      {
        "label": "AO 190 - Record of the Number of Grand Jurors Concurring in an Indictment",
        "url": "https://www.uscourts.gov/sites/default/files/ao190.pdf"
      },
      {
        "label": "AO 191 - Report of a Grand Jury's Failure to Concur in an Indictment",
        "url": "https://www.uscourts.gov/sites/default/files/ao191.pdf"
      },
      {
        "label": "AO 199A - Order Setting Conditions of Release",
        "url": "https://www.uscourts.gov/sites/default/files/ao199a.pdf"
      },
      {
        "label": "AO 199B - Additional Conditions of Release",
        "url": "https://www.uscourts.gov/sites/default/files/ao199b.pdf"
      },
      {
        "label": "AO 199C - Advice of Penalties/Acknowledgment",
        "url": "https://www.uscourts.gov/sites/default/files/ao199c.pdf"
      },
      {
        "label": "AO 245B - Judgment in a Criminal Case",
        "url": "https://www.uscourts.gov/sites/default/files/ao245b.pdf"
      },
      {
        "label": "AO 245C - Amended Judgment in Criminal Case",
        "url": "https://www.uscourts.gov/sites/default/files/ao245c.pdf"
      },
      {
        "label": "AO 245D - Judgment in a Criminal Case (for Revocation of Probation or Supervised Release)",
        "url": "https://www.uscourts.gov/sites/default/files/ao245d.pdf"
      },
      {
        "label": "AO 245E - Judgment in a Criminal Case (for Organizational Defendants)",
        "url": "https://www.uscourts.gov/sites/default/files/ao245e.pdf"
      },
      {
        "label": "AO 245SOR - Judgment in a Criminal Case (Statement of Reasons)",
        "url": "https://www.uscourts.gov/sites/default/files/ao245sor.pdf"
      },
      {
        "label": "AO 246 - Probation Order Under 18 U.S.C. 3607",
        "url": "https://www.uscourts.gov/sites/default/files/ao246.pdf"
      },
      {
        "label": "AO 246A - Order of Discharge and Dismissal Under 18 U. S. C. 3607(a)",
        "url": "https://www.uscourts.gov/sites/default/files/ao246a.pdf"
      },
      {
        "label": "AO 246B - Order for a Presentence Investigation and Report",
        "url": "https://www.uscourts.gov/sites/default/files/ao246b.pdf"
      },
      {
        "label": "AO 247 - Order Regarding Motion for Sentence Reduction Pursuant to 18 U.S.C. 3582(c)(2)",
        "url": "https://www.uscourts.gov/sites/default/files/ao_247_0.pdf"
      },
      {
        "label": "AO 248 - Order on Motion for Sentence Reduction Under 18 U.S.C. 3582(c)(1)(A)",
        "url": "https://www.uscourts.gov/sites/default/files/ao_248.pdf"
      },
      {
        "label": "AO 249 - Drug Offender's Reinstatement of Federal Benefits",
        "url": "https://www.uscourts.gov/sites/default/files/ao249.pdf"
      },
      {
        "label": "AO 250 - Motion for Sentence Reduction Under 18 U.S.C. 3582(c)(1)(A)",
        "url": "https://www.uscourts.gov/sites/default/files/ao-250.pdf"
      },
      {
        "label": "AO 442 - Arrest Warrant",
        "url": "https://www.uscourts.gov/sites/default/files/ao442.pdf"
      },
      {
        "label": "AO 443 - Warrant for the Arrest of a Witness or Material Witness in a Pending Criminal Case",
        "url": "https://www.uscourts.gov/sites/default/files/ao443.pdf"
      },
      {
        "label": "AO 444 - Warrant for the Arrest of a Witness in a Grand Jury Proceeding (Under Seal)",
        "url": "https://www.uscourts.gov/sites/default/files/ao444.pdf"
      },
      {
        "label": "AO 455 - Waiver of an Indictment",
        "url": "https://www.uscourts.gov/sites/default/files/ao455.pdf"
      },
      {
        "label": "AO 466 - Waiver of Rule 32.1 Hearing",
        "url": "https://www.uscourts.gov/sites/default/files/ao466.pdf"
      },
      {
        "label": "AO 466A - Waiver of Rule 5 and 5.1 Hearings",
        "url": "https://www.uscourts.gov/sites/default/files/ao466a.pdf"
      },
      {
        "label": "AO 467 - Order Requiring a Defendant to Appear in the District Where Charges are Pending and Transferring Bail",
        "url": "https://www.uscourts.gov/sites/default/files/ao467.pdf"
      },
      {
        "label": "AO 468 - Waiver of a Preliminary Hearing",
        "url": "https://www.uscourts.gov/sites/default/files/ao468.pdf"
      },
      {
        "label": "AO 470 - Order Scheduling a Detention Hearing",
        "url": "https://www.uscourts.gov/sites/default/files/ao470.pdf"
      },
      {
        "label": "AO 471 - Order to Detain a Defendant Temporarily Under 18 U.S.C. 3142(d)",
        "url": "https://www.uscourts.gov/sites/default/files/ao471.pdf"
      },
      {
        "label": "AO 472 - Order of Detention Pending Trial",
        "url": "https://www.uscourts.gov/sites/default/files/document/ao-472.pdf"
      },
      {
        "label": "AO 83 - Summons in a Criminal Case",
        "url": "https://www.uscourts.gov/sites/default/files/ao083.pdf"
      },
      {
        "label": "AO 86A - Consent to Proceed Before a Magistrate Judge in a Misdemeanor Case",
        "url": "https://www.uscourts.gov/sites/default/files/ao086a.pdf"
      },
      {
        "label": "AO 89 - Subpoena to Testify at a Hearing or Trial in a Criminal Case",
        "url": "https://www.uscourts.gov/sites/default/files/ao089.pdf"
      },
      {
        "label": "AO 89B - Subpoena to Produce Documents, Information, or Objects in a Criminal Case",
        "url": "https://www.uscourts.gov/sites/default/files/ao_089b_0.pdf"
      },
      {
        "label": "AO 90 - Subpoena to Testify at a Deposition in a Criminal Case",
        "url": "https://www.uscourts.gov/sites/default/files/ao090.pdf"
      },
      {
        "label": "AO 91 - Criminal Complaint",
        "url": "https://www.uscourts.gov/sites/default/files/ao091.pdf"
      },
      {
        "label": "AO 93 - Search and Seizure Warrant",
        "url": "https://www.uscourts.gov/sites/default/files/ao093.pdf"
      },
      {
        "label": "AO 93A - Search and Seizure Warrant on Oral Testimony",
        "url": "https://www.uscourts.gov/sites/default/files/ao093a.pdf"
      },
      {
        "label": "AO 93B - Anticipatory Search and Seizure Warrant",
        "url": "https://www.uscourts.gov/sites/default/files/ao093b.pdf"
      },
      {
        "label": "AO 93C - Warrant by Telephone or Other Reliable Electronic Means",
        "url": "https://www.uscourts.gov/sites/default/files/ao_093c_0818_0.pdf"
      },
      {
        "label": "AO 94 - Commitment to Another District",
        "url": "https://www.uscourts.gov/sites/default/files/ao094.pdf"
      },
      {
        "label": "AO 98 - Appearance Bond",
        "url": "https://www.uscourts.gov/sites/default/files/ao098.pdf"
      },
      {
        "label": "AO 99 - Appearance Bond of Witness",
        "url": "https://www.uscourts.gov/sites/default/files/ao099.pdf"
      },
      {
        "label": "AO-0245SOR (Org.) - Judgment in a Criminal Case for Organizational Defendants Attachment - Statement of Reasons",
        "url": "https://www.uscourts.gov/sites/default/files/document/ao245sor-org-updatedsept15-finalversion.pdf"
      }
    ]
  },
  "hipaa": {
    "key": "hipaa",
    "label": "HIPAA",
    "sourceFile": "form_catalog/hipaa/links.txt",
    "links": [
      {
        "label": "Sample HIPAA Authorization for Research (HHS Office for Civil Rights)",
        "url": "https://www.hhs.gov/sites/default/files/ocr/privacy/hipaa/understanding/special/research/authorization.pdf"
      },
      {
        "label": "HIPAA for Professionals — OCR privacy guidance",
        "url": "https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/research/index.html"
      },
      {
        "label": "45 CFR 164.508 — Uses and disclosures for which an authorization is required",
        "url": "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E/section-164.508"
      },
      {
        "label": "Model HHS Notices of Privacy Practices",
        "url": "https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/model-notices-privacy-practices/index.html"
      }
    ]
  },
  "nar_realtor": {
    "key": "nar_realtor",
    "label": "NAR / Realtor",
    "sourceFile": "form_catalog/nar_realtor/links.txt",
    "links": [
      {
        "label": "California (C.A.R.)",
        "url": "https://www.car.org/riskmanagement/tools/transactions"
      },
      {
        "label": "Texas (TAR)",
        "url": "https://www.texasrealestate.com/forms-and-contracts"
      },
      {
        "label": "Florida (FR)",
        "url": "https://www.floridarealtors.org/tools-research/forms"
      },
      {
        "label": "New York (NYSAR)",
        "url": "https://www.nysar.com/tools/forms-library"
      },
      {
        "label": "Illinois",
        "url": "https://www.illinoisrealtors.org/member-services/forms-contracts"
      },
      {
        "label": "Pennsylvania",
        "url": "https://www.parealtors.org/forms"
      },
      {
        "label": "Ohio",
        "url": "https://www.ohiorealtors.org/standard-forms"
      },
      {
        "label": "Georgia",
        "url": "https://www.garealtor.com/real-estate-forms-2"
      },
      {
        "label": "North Carolina",
        "url": "https://www.ncrealtors.org/forms"
      },
      {
        "label": "Massachusetts",
        "url": "https://www.marealtor.com/tools-services/forms"
      },
      {
        "label": "Arizona",
        "url": "https://www.aaronline.com/resources/forms"
      },
      {
        "label": "Virginia",
        "url": "https://www.virginiarealtors.org/forms"
      },
      {
        "label": "Washington (NWMLS)",
        "url": "https://www.nwmls.com/forms"
      },
      {
        "label": "Colorado",
        "url": "https://www.coloradorealtors.com/forms"
      },
      {
        "label": "Oregon",
        "url": "https://www.oregonrealtors.org/forms"
      },
      {
        "label": "New Jersey",
        "url": "https://www.njrealtor.com/forms"
      }
    ]
  }
};
