const commonRelatedDocs = ['getting-started', 'editor-workflow', 'search-fill'];

const buildOpportunityPage = (page) => {
  const sourceLabel = page.sourceLabel ?? 'source data';
  const workflowLabel = page.workflowLabel ?? 'PDF workflow';
  const outputLabel = page.outputLabel ?? 'filled PDF output';
  const boundary = page.boundary ?? 'Keep the page focused on reviewed fixed-layout PDF templates, not general document design.';

  return {
    key: page.key,
    category: 'workflow',
    path: page.path,
    navLabel: page.navLabel,
    heroTitle: page.heroTitle,
    heroSummary: page.heroSummary,
    seoTitle: page.seoTitle ?? `${page.heroTitle} | DullyPDF`,
    seoDescription: page.seoDescription ?? page.heroSummary,
    seoKeywords: page.seoKeywords,
    valuePoints: page.valuePoints,
    proofPoints: page.proofPoints,
    articleSections: [
      {
        title: `When ${page.navLabel.toLowerCase()} is the right DullyPDF workflow`,
        paragraphs: [
          `${page.intentSummary} DullyPDF fits this search when the final output must stay on an existing PDF layout instead of becoming a redesigned document.`,
          `${page.fitSummary} The work starts with a reviewed template, because source data is only useful after the PDF field names, field types, and output mode are predictable.`,
        ],
      },
      {
        title: `Set up the ${workflowLabel} before filling records`,
        paragraphs: [
          page.setupSummary,
          'A practical setup pass is to upload the PDF, review detection, rename or map fields, run one representative fill, and save the template before publishing links, API endpoints, or repeat packet workflows.',
        ],
        bullets: page.setupBullets,
      },
      {
        title: `Choose the right runtime for ${page.navLabel.toLowerCase()}`,
        paragraphs: [
          `The safest first runtime is usually Search & Fill when a person still needs to inspect ${sourceLabel}, choose one record, and compare the result against the original PDF. That keeps the first production decision close to the document instead of hiding it behind an automation rule too early.`,
          `API Fill is the better runtime only after another system already owns the record and can send clean JSON to a published template endpoint. Fill By Link is a different path again: use it when the record does not exist yet and a respondent should submit the answers before DullyPDF creates ${outputLabel}.`,
        ],
      },
      {
        title: `Map ${sourceLabel} into stable PDF fields`,
        paragraphs: [
          page.mappingSummary,
          'The fragile parts are usually not the HTTP request or the file upload. They are duplicate field names, ambiguous checkbox values, inconsistent dates, missing required fields, and output that only looks correct in one PDF viewer.',
        ],
        bullets: page.mappingBullets,
      },
      {
        title: `Keep ${sourceLabel} and PDF schema boundaries explicit`,
        paragraphs: [
          `${boundary} The source should be treated as structured values that land in reviewed fields, not as permission to redesign the PDF, invent missing sections, or rely on a viewer-specific behavior that only works during setup.`,
          'For Search & Fill, prefer source files that contain actual row values: CSV, XLSX, or JSON. SQL and TXT imports should be treated as schema-only mapping inputs, while database-backed automation should query the database itself and send JSON through API Fill.',
        ],
      },
      {
        title: 'Review output before scaling the workflow',
        paragraphs: [
          page.qaSummary,
          `A useful QA row includes blanks, long names, date values, checkbox or radio choices, and at least one value that is easy to verify visually in ${outputLabel}. If that row fails, fix the template or mapping before adding volume.`,
        ],
      },
      {
        title: `What makes ${page.navLabel.toLowerCase()} production-ready`,
        paragraphs: [
          `A production-ready ${workflowLabel} has a saved template, stable field names, known source headers, tested checkbox or radio rules, and an output choice that matches the recipient. Editable output is useful for internal follow-up, while flat output is usually safer for final records shared outside the workspace.`,
          'The handoff is ready when an operator can clear the form, rerun the same record, and get the same result without remembering hidden cleanup steps. That repeatability is the real SEO promise behind the page: not just filling one PDF, but making the workflow dependable enough to reuse.',
        ],
      },
    ],
    faqs: page.faqs,
    relatedIntentPages: page.relatedIntentPages,
    relatedDocs: page.relatedDocs ?? commonRelatedDocs,
  };
};

const sourceSystemPages = [
  {
    key: 'fill-pdf-from-google-sheets',
    path: '/fill-pdf-from-google-sheets',
    navLabel: 'Google Sheets to PDF',
    heroTitle: 'Fill PDF Forms From Google Sheets Data',
    heroSummary:
      'Use Google Sheets rows as the source data for reviewed DullyPDF templates through CSV/XLSX export, Search & Fill, or API Fill.',
    seoKeywords: ['fill pdf from google sheets', 'google sheets to pdf form', 'populate pdf from google sheets', 'google sheets pdf template', 'spreadsheet to fillable pdf'],
    valuePoints: ['Reuse a fixed PDF template instead of copying rows into a document by hand.', 'Search and review one row before producing the final PDF.', 'Move to API Fill when a backend or automation already shapes the row as JSON.'],
    proofPoints: ['DullyPDF Search & Fill supports CSV, XLSX, and JSON rows.', 'Row data stays in the browser for Search & Fill.', 'Saved templates preserve mapping and fill rules for repeat use.'],
    intentSummary: 'Teams keep client, patient, student, vendor, or job data in Google Sheets and need that row data placed into a PDF they already use.',
    fitSummary: 'The strongest fit is a stable sheet export feeding a stable saved template.',
    setupSummary: 'Use the Google Sheet as the operational table, then export the relevant view to CSV or XLSX before opening Search & Fill.',
    setupBullets: ['Keep one header row with stable column names.', 'Use a representative row with long names, dates, and checkbox values for testing.', 'Save the DullyPDF template after the field map is reviewed.'],
    mappingSummary: 'Map sheet headers to PDF field names, then use Search & Fill to choose the row and inspect the output before download.',
    mappingBullets: ['Normalize date columns before upload.', 'Avoid duplicate headers that collapse into ambiguous field names.', 'Use explicit checkbox tokens such as yes/no, true/false, or defined option values.'],
    qaSummary: 'Test the exported sheet with one realistic row, clear the document, and refill it to verify the mapping is repeatable.',
    boundary: 'DullyPDF does not read private Google Sheets directly from this page. Treat Google Sheets as a source that exports rows or feeds an API call.',
    faqs: [
      { question: 'Can DullyPDF fill a PDF directly from Google Sheets?', answer: 'DullyPDF can fill from CSV/XLSX exports of Google Sheets data, or from JSON sent to API Fill by your own automation.' },
      { question: 'Is a native Google Sheets add-on required?', answer: 'No. The practical no-code path is exporting rows and using Search & Fill.' },
      { question: 'When should I use API Fill instead?', answer: 'Use API Fill when another system already has the row and should call a template endpoint without an operator selecting it manually.' },
    ],
    relatedIntentPages: ['fill-pdf-from-csv', 'excel-to-fillable-pdf-template', 'pdf-to-database-template', 'webhook-json-to-pdf-form'],
  },
  {
    key: 'airtable-to-pdf-template',
    path: '/airtable-to-pdf-template',
    navLabel: 'Airtable to PDF',
    heroTitle: 'Fill Existing PDF Templates From Airtable Records',
    heroSummary:
      'Turn Airtable records into filled PDFs by exporting views to CSV or sending record-shaped JSON to a saved DullyPDF template endpoint.',
    seoKeywords: ['airtable to pdf template', 'airtable pdf form', 'generate pdf from airtable record', 'fill pdf from airtable', 'airtable records to pdf'],
    valuePoints: ['Keep Airtable as the source of record while DullyPDF preserves the approved PDF layout.', 'Use CSV exports for reviewed Search & Fill workflows.', 'Use API Fill when Airtable automations or scripts can send JSON.'],
    proofPoints: ['Airtable grid views can export visible fields to CSV.', 'DullyPDF maps CSV headers to PDF fields.', 'API Fill exposes a stable schema for system-to-system generation.'],
    intentSummary: 'Airtable users often need a record, client, asset, applicant, or job row rendered into an existing PDF form.',
    fitSummary: 'DullyPDF is a better fit when the PDF layout is fixed and approved, not when the user wants a new variable-length document designer.',
    setupSummary: 'Create a filtered Airtable view with only the fields needed for the PDF, then export it for Search & Fill or shape the record as JSON for API Fill.',
    setupBullets: ['Choose human-readable field names in the view.', 'Resolve linked-record text before export when possible.', 'Keep attachment handling separate from ordinary scalar field values.'],
    mappingSummary: 'Use Airtable field names as schema headers and map them to reviewed DullyPDF field names.',
    mappingBullets: ['Test select and multi-select values against checkbox or radio rules.', 'Use flat output for final records shared outside the team.', 'Use group templates when one Airtable record fills a packet.'],
    qaSummary: 'Preview the filled PDF from one real record before adding an Airtable script, button, or automation around the API call.',
    boundary: 'Do not present this as a native Airtable extension. It is a CSV, XLSX, JSON, or API workflow built around saved DullyPDF templates.',
    faqs: [
      { question: 'Can Airtable records fill an existing PDF?', answer: 'Yes. Export a view to CSV for Search & Fill, or send record data as JSON to a published API Fill endpoint.' },
      { question: 'Does DullyPDF design Airtable documents from scratch?', answer: 'No. DullyPDF is strongest when an existing fixed-layout PDF must be filled from Airtable data.' },
      { question: 'Can one Airtable record fill multiple PDFs?', answer: 'Yes, if the PDFs are saved in a DullyPDF group and the shared fields are mapped consistently.' },
    ],
    relatedIntentPages: ['fill-pdf-from-csv', 'pdf-fill-api', 'one-json-fill-multiple-pdfs', 'pdf-packet-workflow'],
  },
  {
    key: 'google-forms-to-filled-pdf',
    path: '/google-forms-to-filled-pdf',
    navLabel: 'Google Forms to PDF',
    heroTitle: 'Turn Google Forms Responses Into Filled PDFs',
    heroSummary:
      'Use Google Forms responses as source data for existing PDF templates through Sheets export, Search & Fill, or API-driven generation.',
    seoKeywords: ['google forms to filled pdf', 'google forms responses to pdf template', 'google form to fillable pdf', 'google forms pdf automation', 'google forms to existing pdf'],
    valuePoints: ['Collect answers in Google Forms while keeping the final output on an approved PDF.', 'Map response columns to PDF fields once and reuse the template.', 'Choose DullyPDF Fill By Link when you want the respondent form and PDF workflow in one product.'],
    proofPoints: ['Search & Fill supports spreadsheet rows exported from form responses.', 'Fill By Link stores respondent submissions directly inside DullyPDF.', 'Flat PDF output avoids browser PDF viewer inconsistencies for recipients.'],
    intentSummary: 'Google Forms is often the easiest intake tool, but many teams still need a completed PDF in a specific layout.',
    fitSummary: 'DullyPDF handles the PDF side of that workflow after responses become rows or JSON.',
    setupSummary: 'Connect the Google Form to its response sheet, clean the question headers, and map those headers to a saved DullyPDF template.',
    setupBullets: ['Use short, stable question labels where possible.', 'Export responses to CSV/XLSX for manual review.', 'Use Fill By Link instead when DullyPDF should own the respondent collection step.'],
    mappingSummary: 'Treat each response row as a structured record and fill the reviewed PDF from that record.',
    mappingBullets: ['Map yes/no and multiple-choice answers deliberately.', 'Check date and phone formatting before output.', 'Use respondent review when the PDF is customer-facing.'],
    qaSummary: 'Run a test response through the full path before relying on automatic generation.',
    boundary: 'DullyPDF does not directly ingest Google Forms responses from this page. Use export, middleware, or DullyPDF Fill By Link.',
    faqs: [
      { question: 'Can Google Forms responses populate an existing PDF?', answer: 'Yes, after those responses are exported to rows or sent as JSON to a DullyPDF API endpoint.' },
      { question: 'Should I use DullyPDF Fill By Link instead?', answer: 'Use Fill By Link when you want DullyPDF to collect the respondent data and keep the response records tied to the template.' },
      { question: 'Can the respondent download a PDF after submitting?', answer: 'DullyPDF supports respondent PDF downloads for supported Fill By Link template workflows.' },
    ],
    relatedIntentPages: ['turn-pdf-into-online-form', 'fill-pdf-from-google-sheets', 'fill-pdf-by-link', 'respondent-download-filled-pdf'],
  },
  {
    key: 'microsoft-forms-to-filled-pdf',
    path: '/microsoft-forms-to-filled-pdf',
    navLabel: 'Microsoft Forms to PDF',
    heroTitle: 'Turn Microsoft Forms Responses Into Filled PDFs',
    heroSummary:
      'Fill existing PDF templates from Microsoft Forms responses by exporting to Excel or routing response data through Power Automate and API Fill.',
    seoKeywords: ['microsoft forms to filled pdf', 'microsoft forms responses to pdf', 'microsoft forms pdf template', 'forms to pdf power automate', 'excel responses to pdf form'],
    valuePoints: ['Use Excel response rows as a clean source for Search & Fill.', 'Use Power Automate and API Fill for system-driven output.', 'Generate flat PDFs for recipient-friendly sharing across Microsoft 365 workflows.'],
    proofPoints: ['Microsoft Forms exposes response data through Excel exports.', 'DullyPDF Search & Fill supports XLSX rows.', 'API Fill accepts strict JSON payloads from automation tools.'],
    intentSummary: 'Microsoft Forms users often need an official or internal PDF copy after someone submits a form.',
    fitSummary: 'DullyPDF fits when the output should be an existing fillable or fixed-layout PDF rather than a printed response report.',
    setupSummary: 'Export response data to Excel for a reviewed workflow, or use Power Automate to shape response values into the JSON expected by API Fill.',
    setupBullets: ['Keep Excel headers stable.', 'Normalize choice, checkbox, and date values before mapping.', 'Save the DullyPDF template before building the automation around it.'],
    mappingSummary: 'Map Excel response columns to PDF fields, then produce flat or editable output depending on the recipient needs.',
    mappingBullets: ['Use flat PDFs for final records and email attachments.', 'Use editable PDFs only when the next person must keep working in live fields.', 'Use a one-record test before broad rollout.'],
    qaSummary: 'Check output in more than one viewer if the PDF will be opened in Outlook, Teams, browser preview, or mobile apps.',
    boundary: 'This is not a native Microsoft Forms app. It is an Excel export or HTTP API workflow.',
    faqs: [
      { question: 'Can Microsoft Forms responses fill a PDF?', answer: 'Yes. Export responses to Excel for Search & Fill, or route response data through Power Automate to API Fill.' },
      { question: 'Does DullyPDF replace Microsoft Forms?', answer: 'No. DullyPDF fills the PDF template. Fill By Link is the DullyPDF-native respondent collection alternative.' },
      { question: 'What output should I send to respondents?', answer: 'Use flat PDF output when the completed record should display reliably outside your editing workflow.' },
    ],
    relatedIntentPages: ['power-automate-fill-pdf-template', 'excel-to-fillable-pdf-template', 'flat-vs-editable-pdf', 'filled-pdf-fields-not-showing'],
  },
  {
    key: 'typeform-to-pdf-template',
    path: '/typeform-to-pdf-template',
    navLabel: 'Typeform to PDF',
    heroTitle: 'Turn Typeform Responses Into Existing PDF Templates',
    heroSummary:
      'Use exported Typeform responses or response API data to fill reviewed DullyPDF templates without rebuilding the final document layout.',
    seoKeywords: ['typeform to pdf template', 'typeform responses to pdf', 'fill pdf from typeform', 'typeform pdf automation', 'typeform to existing pdf'],
    valuePoints: ['Keep Typeform as the front-end experience while preserving your existing PDF output.', 'Export CSV/XLSX responses for Search & Fill.', 'Use API Fill when a backend retrieves responses and sends JSON.'],
    proofPoints: ['DullyPDF supports CSV, XLSX, and JSON source records.', 'Saved templates preserve field names and output behavior.', 'Flat PDFs are better for final respondent copies.'],
    intentSummary: 'Typeform is strong for respondent experience, but many organizations still need responses placed into a formal PDF template.',
    fitSummary: 'DullyPDF fits after the response exists as a row or JSON record.',
    setupSummary: 'Export responses, map the question columns to PDF fields, and test one response before automating the path.',
    setupBullets: ['Use stable question labels or aliases.', 'Handle multiple-choice values explicitly.', 'Separate file-upload review from ordinary scalar PDF fields.'],
    mappingSummary: 'Use Search & Fill for operator-selected responses, or send response JSON to API Fill when the workflow should run from your backend.',
    mappingBullets: ['Review long text fields for overflow.', 'Use flat output for signed or final records.', 'Keep Typeform file uploads out of automatic image-field claims unless you process them deliberately.'],
    qaSummary: 'A completed Typeform response is not automatically a production PDF. Inspect one filled output against the source answers first.',
    boundary: 'DullyPDF does not provide a native Typeform connector in this page. It uses exported rows, response API data, or the DullyPDF-native Fill By Link alternative.',
    faqs: [
      { question: 'Can Typeform responses fill an existing PDF?', answer: 'Yes, after responses are exported to CSV/XLSX or sent as JSON to API Fill.' },
      { question: 'Can Typeform file uploads populate image fields automatically?', answer: 'Not automatically. File uploads should be reviewed and handled as a separate workflow.' },
      { question: 'When is Fill By Link better?', answer: 'Use Fill By Link when you want DullyPDF to collect responses and generate filled PDFs from the same saved template workflow.' },
    ],
    relatedIntentPages: ['turn-pdf-into-online-form', 'fill-pdf-from-csv', 'pdf-fill-api', 'fill-pdf-by-link'],
  },
  {
    key: 'hubspot-to-pdf-template',
    path: '/hubspot-to-pdf-template',
    navLabel: 'HubSpot to PDF',
    heroTitle: 'Fill Existing PDF Templates From HubSpot CRM Data',
    heroSummary:
      'Use HubSpot contact, company, deal, ticket, or custom-object data to call a DullyPDF API Fill endpoint for fixed PDF templates.',
    seoKeywords: ['hubspot to pdf template', 'hubspot pdf generator', 'hubspot data to pdf', 'hubspot form submission to pdf', 'hubspot crm pdf automation'],
    valuePoints: ['Render CRM data into existing PDF forms and packets.', 'Use API Fill when HubSpot workflows or middleware can send JSON.', 'Keep final output on approved PDF layouts instead of rebuilding documents from scratch.'],
    proofPoints: ['API Fill publishes a template-scoped schema and key.', 'DullyPDF supports flat final PDFs for recipient sharing.', 'Group API Fill can return a packet ZIP from one record.'],
    intentSummary: 'HubSpot teams often need CRM values turned into quotes, agreements, intake PDFs, invoices, or internal approval forms.',
    fitSummary: 'DullyPDF fits when the destination is an existing PDF template with stable fields.',
    setupSummary: 'Publish a DullyPDF API Fill endpoint, map HubSpot properties to the public schema, and have middleware or a workflow call the endpoint.',
    setupBullets: ['Start with one object type and one template.', 'Name PDF fields after the HubSpot properties or mapped schema keys.', 'Use group API Fill when one deal or contact should generate a packet.'],
    mappingSummary: 'Shape HubSpot values into the top-level API Fill `data` object and let DullyPDF materialize the PDF from the saved template snapshot.',
    mappingBullets: ['Handle line-item totals before the API call unless using DullyPDF calculation fields.', 'Check choice values against checkbox and radio rules.', 'Store returned PDFs in the CRM only after validating output.'],
    qaSummary: 'Run one known HubSpot record through a staging endpoint before wiring the workflow into live CRM automation.',
    boundary: 'Do not present this as a HubSpot marketplace app. It is an API integration pattern for teams that can send JSON.',
    faqs: [
      { question: 'Can HubSpot data fill a PDF template?', answer: 'Yes, when HubSpot data is sent as JSON to a DullyPDF API Fill endpoint.' },
      { question: 'Does DullyPDF create HubSpot proposals from scratch?', answer: 'No. This workflow is for existing fixed PDF templates that should receive HubSpot values.' },
      { question: 'Can one HubSpot deal generate multiple PDFs?', answer: 'Yes, use saved template groups and group API Fill when one record should produce a packet.' },
    ],
    relatedIntentPages: ['webhook-json-to-pdf-form', 'pdf-fill-api', 'one-json-fill-multiple-pdfs', 'pdf-estimate-quote-calculations'],
  },
  {
    key: 'notion-database-to-pdf-form',
    path: '/notion-database-to-pdf-form',
    navLabel: 'Notion Database to PDF',
    heroTitle: 'Fill Existing PDF Forms From a Notion Database',
    heroSummary:
      'Use Notion database records as structured source data for fixed PDF templates through export, middleware, or DullyPDF API Fill.',
    seoKeywords: ['notion database to pdf form', 'notion to pdf template', 'fill pdf from notion database', 'notion records to pdf', 'notion pdf automation'],
    valuePoints: ['Keep planning and client data in Notion while generating official PDFs elsewhere.', 'Use CSV export for reviewed Search & Fill workflows.', 'Use API Fill when a backend reads Notion and sends JSON.'],
    proofPoints: ['DullyPDF templates preserve field mapping and output behavior.', 'Search & Fill handles CSV/XLSX/JSON rows.', 'API Fill accepts JSON from external systems.'],
    intentSummary: 'Notion users often want database records to become client, project, inspection, or internal PDFs.',
    fitSummary: 'DullyPDF fits when the final output is an existing form, not a printed Notion page.',
    setupSummary: 'Export records or use middleware to turn Notion properties into the field keys expected by a saved DullyPDF template.',
    setupBullets: ['Flatten relations and rollups before filling when possible.', 'Keep rich Notion page content out of fixed PDF fields unless summarized.', 'Use one sample record to prove field length and formatting.'],
    mappingSummary: 'Map Notion properties to PDF field names, then fill the template from rows or API JSON.',
    mappingBullets: ['Use date and select values consistently.', 'Avoid dynamic repeating sections in fixed PDFs.', 'Use flat output for final records.'],
    qaSummary: 'Inspect output with records that contain long names, blank optional properties, and select values.',
    boundary: 'DullyPDF does not preserve Notion page formatting. It fills existing PDFs from structured values.',
    faqs: [
      { question: 'Can a Notion database fill a PDF form?', answer: 'Yes, if the database values are exported or sent as JSON to DullyPDF.' },
      { question: 'Is this the same as exporting a Notion page to PDF?', answer: 'No. DullyPDF fills an existing PDF template from structured Notion properties.' },
      { question: 'Can Notion records generate PDF packets?', answer: 'Yes, if your integration sends one JSON record to a DullyPDF group API endpoint.' },
    ],
    relatedIntentPages: ['fill-pdf-from-csv', 'webhook-json-to-pdf-form', 'no-code-pdf-automation', 'save-reusable-pdf-template'],
  },
  {
    key: 'salesforce-to-pdf-template',
    path: '/salesforce-to-pdf-template',
    navLabel: 'Salesforce to PDF',
    heroTitle: 'Fill Existing PDF Templates From Salesforce Data',
    heroSummary:
      'Send Salesforce record data to a saved DullyPDF API Fill endpoint when contacts, claims, applications, or deals must become fixed PDFs.',
    seoKeywords: ['salesforce to pdf template', 'salesforce fill pdf form', 'salesforce data to pdf', 'salesforce pdf automation', 'populate pdf from salesforce'],
    valuePoints: ['Use Salesforce as the source system and DullyPDF as the PDF template materializer.', 'Fill official, carrier, HR, finance, or internal PDF templates without rebuilding them.', 'Use group endpoints when one Salesforce record needs a packet.'],
    proofPoints: ['API Fill exposes a schema for each saved template endpoint.', 'DullyPDF supports checkbox, radio, text, and calculated output behavior during materialization.', 'Generated PDFs can be flat for final sharing.'],
    intentSummary: 'Salesforce teams often need CRM or case data placed into PDFs that already exist outside Salesforce.',
    fitSummary: 'DullyPDF fits when a system can send JSON and wants the PDF layer handled by a reviewed template.',
    setupSummary: 'Publish the DullyPDF endpoint, map Salesforce fields to the endpoint schema, and call it from middleware, OmniStudio, Apex, or another approved integration layer.',
    setupBullets: ['Start with a non-production template endpoint.', 'Normalize picklist values for checkbox/radio fields.', 'Keep source PDF revisions under template review.'],
    mappingSummary: 'Transform Salesforce record fields into API Fill JSON and download or store the returned PDF.',
    mappingBullets: ['Check required fields before calling the endpoint.', 'Use one record with realistic data for output QA.', 'Use groups for packets instead of concatenating unrelated PDFs manually.'],
    qaSummary: 'Validate field values, appearance, and flat output before attaching generated PDFs to live Salesforce records.',
    boundary: 'DullyPDF is not claiming an AppExchange package or Salesforce-native UI. This is an API-based PDF fill workflow.',
    faqs: [
      { question: 'Can Salesforce data populate an existing PDF?', answer: 'Yes, when your Salesforce workflow sends JSON to a DullyPDF API Fill endpoint.' },
      { question: 'Does DullyPDF require Acrobat inside Salesforce?', answer: 'No. The PDF template is prepared in DullyPDF and filled through an HTTP endpoint.' },
      { question: 'Can Salesforce generate packets?', answer: 'Yes, with DullyPDF saved template groups and group API Fill.' },
    ],
    relatedIntentPages: ['pdf-fill-api', 'one-json-fill-multiple-pdfs', 'insurance-pdf-automation', 'finance-loan-pdf-automation'],
  },
];

const automationPages = [
  {
    key: 'power-automate-fill-pdf-template',
    path: '/power-automate-fill-pdf-template',
    navLabel: 'Power Automate PDF Fill',
    heroTitle: 'Fill Existing PDF Templates From Power Automate',
    heroSummary:
      'Use Power Automate to collect Microsoft 365 data, shape JSON, call DullyPDF API Fill, and store or email the returned PDF.',
    seoKeywords: ['power automate fill pdf template', 'power automate pdf form', 'power automate fill existing pdf', 'microsoft flow fill pdf', 'power automate json to pdf'],
    valuePoints: ['Keep Power Automate as the workflow orchestrator.', 'Use DullyPDF for fixed PDF template filling instead of Word-template workarounds.', 'Return flat PDFs that are easier to share and archive.'],
    proofPoints: ['API Fill is a normal HTTPS endpoint.', 'Public schemas expose expected field names and types.', 'Strict request validation catches misspelled top-level keys.'],
    intentSummary: 'Power Automate users frequently need Microsoft Forms, SharePoint, Excel, or Dataverse data to become a completed PDF.',
    fitSummary: 'DullyPDF fits when the PDF already exists and should be filled, not redesigned as a Word document.',
    setupSummary: 'Use Power Automate to gather values, compose the `data` object, and call the DullyPDF endpoint with the template key.',
    setupBullets: ['Publish the endpoint from a saved template.', 'Copy the schema and example payload before building the flow.', 'Store the returned PDF in SharePoint, OneDrive, or email only after testing.'],
    mappingSummary: 'Power Automate should transform source values into DullyPDF field names before the HTTP action runs.',
    mappingBullets: ['Normalize booleans and choice fields.', 'Send dates in a predictable format.', 'Use flat output for external recipients.'],
    qaSummary: 'Run the flow with one known record and compare the returned PDF against the source values before enabling production triggers.',
    boundary: 'Do not call this a first-party Power Automate connector. It is an HTTP API pattern.',
    faqs: [
      { question: 'Can Power Automate call DullyPDF?', answer: 'Yes, when your flow can send an authenticated HTTP request to an API Fill endpoint.' },
      { question: 'Is this different from Word template generation?', answer: 'Yes. DullyPDF fills an existing PDF template instead of generating a document from a Word template.' },
      { question: 'Can the flow store the generated PDF?', answer: 'Yes. After the HTTP response returns the PDF bytes, your flow can store or email them according to your Microsoft 365 setup.' },
    ],
    relatedIntentPages: ['pdf-fill-api', 'microsoft-forms-to-filled-pdf', 'csharp-fill-pdf-api', 'webhook-json-to-pdf-form'],
    relatedDocs: ['api-fill', 'search-fill', 'troubleshooting'],
  },
  {
    key: 'zapier-webhook-to-pdf',
    path: '/zapier-webhook-to-pdf',
    navLabel: 'Zapier Webhook to PDF',
    heroTitle: 'Generate Filled PDFs From Zapier Webhooks',
    heroSummary:
      'Use a Zapier webhook or custom request to send structured data to a DullyPDF API Fill endpoint and receive a filled PDF.',
    seoKeywords: ['zapier webhook to pdf', 'zapier generate filled pdf', 'zapier pdf template', 'zapier json to pdf', 'zapier fill pdf form'],
    valuePoints: ['Connect no-code triggers to a stable PDF fill endpoint.', 'Map Zapier fields to the DullyPDF public schema.', 'Use one tested PDF template instead of rebuilding the same output in every Zap.'],
    proofPoints: ['API Fill accepts JSON over HTTPS.', 'Endpoint keys can be rotated or revoked.', 'Audit activity summarizes recent endpoint behavior.'],
    intentSummary: 'Zapier users often have data from forms, CRMs, or spreadsheets and need that data to produce a PDF.',
    fitSummary: 'DullyPDF fits when the output is an existing PDF form and the Zap can send JSON.',
    setupSummary: 'Publish an API Fill endpoint, copy the example request, and configure Zapier to send the mapped field values.',
    setupBullets: ['Use a test endpoint first.', 'Keep field names aligned with the public schema.', 'Store the generated PDF in the destination app only after validating output.'],
    mappingSummary: 'Zapier should transform trigger fields into the DullyPDF `data` payload rather than forwarding raw app field labels blindly.',
    mappingBullets: ['Handle missing optional values.', 'Normalize checkbox, radio, and date fields.', 'Use a representative trigger sample.'],
    qaSummary: 'Test the Zap with known input, download the PDF, and verify values before switching the Zap on for live data.',
    boundary: 'DullyPDF is not claiming a Zapier app here. This page describes a webhook/custom-request workflow.',
    faqs: [
      { question: 'Can Zapier generate a filled PDF with DullyPDF?', answer: 'Yes, if the Zap sends JSON to a DullyPDF API Fill endpoint and handles the PDF response.' },
      { question: 'Do I need to upload the PDF in every Zap?', answer: 'No. Prepare and save the template in DullyPDF, then call its published endpoint.' },
      { question: 'Can Zapier fill a PDF packet?', answer: 'Yes, when it calls a group API endpoint that returns a ZIP of PDFs.' },
    ],
    relatedIntentPages: ['webhook-json-to-pdf-form', 'pdf-fill-api-curl', 'turn-pdf-into-online-form', 'make-webhook-to-pdf'],
    relatedDocs: ['api-fill', 'troubleshooting', 'getting-started'],
  },
  {
    key: 'make-webhook-to-pdf',
    path: '/make-webhook-to-pdf',
    navLabel: 'Make Webhook to PDF',
    heroTitle: 'Generate Filled PDFs From Make Webhooks',
    heroSummary:
      'Build a Make scenario that transforms incoming records into DullyPDF API Fill JSON and stores the returned filled PDF.',
    seoKeywords: ['make webhook to pdf', 'make.com pdf template', 'make generate filled pdf', 'make json to pdf', 'make fill pdf form'],
    valuePoints: ['Use Make for orchestration and DullyPDF for PDF template filling.', 'Normalize source data before the HTTP request.', 'Generate flat PDFs for stable downstream sharing.'],
    proofPoints: ['DullyPDF endpoints accept strict JSON payloads.', 'Saved templates hold field mapping and output behavior.', 'Group endpoints support packet-style output.'],
    intentSummary: 'Make users often need a scenario that turns webhook, CRM, form, or spreadsheet data into a PDF.',
    fitSummary: 'DullyPDF fits when Make can send JSON to a stable template endpoint.',
    setupSummary: 'Create a scenario with a trigger, transformation step, HTTP request to DullyPDF, and a storage or email step for the PDF response.',
    setupBullets: ['Copy the public schema from the DullyPDF endpoint.', 'Build a small test payload by hand first.', 'Keep binary PDF handling explicit in the destination step.'],
    mappingSummary: 'Make should map app-specific values to the exact field keys expected by the saved template.',
    mappingBullets: ['Convert choice values to radio or checkbox options.', 'Use ISO-style date strings when possible.', 'Send only fields the template expects.'],
    qaSummary: 'Use a controlled scenario run with one known payload before enabling live triggers.',
    boundary: 'This is an HTTP scenario pattern, not a native Make module.',
    faqs: [
      { question: 'Can Make call DullyPDF API Fill?', answer: 'Yes. Use Make HTTP tools to send JSON to the published endpoint.' },
      { question: 'Can Make store the generated PDF?', answer: 'Yes. Make can pass the returned PDF bytes to a storage, email, or CRM step depending on your scenario.' },
      { question: 'What should I test first?', answer: 'Test checkbox, radio, date, and blank optional values because those are the most common mapping issues.' },
    ],
    relatedIntentPages: ['webhook-json-to-pdf-form', 'pdf-fill-api', 'pdf-checkbox-values-csv', 'pdf-date-format-csv-fill'],
    relatedDocs: ['api-fill', 'troubleshooting', 'rename-mapping'],
  },
  {
    key: 'webhook-json-to-pdf-form',
    path: '/webhook-json-to-pdf-form',
    navLabel: 'Webhook JSON to PDF',
    heroTitle: 'Fill Existing PDF Forms From Webhook JSON',
    heroSummary:
      'Send JSON from any webhook-capable system to a saved DullyPDF template endpoint and receive a filled PDF response.',
    seoKeywords: ['webhook json to pdf form', 'json webhook to pdf', 'fill pdf from webhook', 'webhook pdf template', 'json to existing pdf form'],
    valuePoints: ['Use one HTTPS endpoint for any system that can send JSON.', 'Keep the PDF layout stable in DullyPDF while other tools own the trigger.', 'Return filled PDFs without deploying PDF libraries in every automation.'],
    proofPoints: ['API Fill requires a top-level `data` object.', 'Published schemas expose expected fields.', 'Responses are generated from saved template snapshots.'],
    intentSummary: 'Webhook users need a generic way to turn structured event data into a completed PDF.',
    fitSummary: 'DullyPDF fits when the webhook payload can be transformed into the template schema.',
    setupSummary: 'Publish the template endpoint, inspect the schema, and configure the calling system to send a clean JSON payload.',
    setupBullets: ['Use Basic auth with the endpoint key.', 'Keep request shape strict and predictable.', 'Log request ids in the calling system for support.'],
    mappingSummary: 'Convert webhook field names into the field names shown by the DullyPDF schema before posting.',
    mappingBullets: ['Do not send arbitrary raw event payloads as-is.', 'Handle nullable and blank values intentionally.', 'Use group API for packet output.'],
    qaSummary: 'Post a known JSON fixture and compare the output PDF before connecting live webhooks.',
    boundary: 'This endpoint returns generated output for a request. Do not describe it as an asynchronous webhook receiver unless that behavior is implemented.',
    faqs: [
      { question: 'Can any webhook fill a DullyPDF template?', answer: 'Any system that can send authenticated JSON can call API Fill after the payload is mapped to the template schema.' },
      { question: 'What JSON shape does DullyPDF expect?', answer: 'Public fill requests send a top-level `data` object with keys matching the published template schema.' },
      { question: 'Can one webhook create many PDFs?', answer: 'Yes, when it calls a saved group endpoint that returns a packet ZIP.' },
    ],
    relatedIntentPages: ['pdf-fill-api', 'pdf-fill-api-curl', 'one-json-fill-multiple-pdfs', 'zapier-webhook-to-pdf'],
    relatedDocs: ['api-fill', 'troubleshooting', 'rename-mapping'],
  },
];

const developerPages = [
  {
    key: 'php-fill-pdf-api',
    path: '/php-fill-pdf-api',
    navLabel: 'PHP PDF Fill API',
    heroTitle: 'Fill PDFs With PHP Using a JSON-to-PDF API',
    heroSummary:
      'Send JSON from PHP or Laravel to a DullyPDF template endpoint and get back a filled PDF without pdftk, FDF files, or PDF coordinate code.',
    seoKeywords: ['php fill pdf api', 'fill pdf form php', 'php json to pdf form', 'laravel fill pdf template', 'php populate pdf form'],
    valuePoints: ['Use ordinary PHP HTTP requests instead of server PDF binaries.', 'Keep PDF field mapping in DullyPDF.', 'Stream or store the returned PDF in your app.'],
    proofPoints: ['API Fill is language-agnostic HTTPS.', 'The same schema works for curl, Node.js, Python, PHP, and other clients.', 'Flat output helps avoid viewer-specific blank-field issues.'],
    intentSummary: 'PHP developers often find old FDF, pdftk, or library-based advice when they need to fill existing PDF forms.',
    fitSummary: 'DullyPDF fits when the PHP app can send JSON and should not own low-level AcroForm handling.',
    setupSummary: 'Create a saved template in DullyPDF, publish API Fill, then call the endpoint from PHP with the mapped JSON payload.',
    setupBullets: ['Store the endpoint key outside source code.', 'Send `Content-Type: application/json`.', 'Write the PDF response to storage or stream it to the browser.'],
    mappingSummary: 'Let DullyPDF own field names, checkbox/radio rules, and output generation while PHP owns application data.',
    mappingBullets: ['Use associative arrays that mirror the public schema.', 'Validate required app data before the call.', 'Use group endpoints for packet ZIPs.'],
    qaSummary: 'Compare one generated PDF against the source application record before exposing the route to users.',
    boundary: 'Do not present this as a PHP SDK unless one is built. The page should show HTTP examples.',
    faqs: [
      { question: 'Can PHP fill an existing PDF through DullyPDF?', answer: 'Yes. PHP can send JSON to a DullyPDF API Fill endpoint and save the returned PDF.' },
      { question: 'Do I need pdftk or FDF files?', answer: 'No. DullyPDF handles the PDF template side after setup.' },
      { question: 'Does this work with Laravel?', answer: 'Yes. Laravel can call the same HTTPS endpoint from a controller, job, or service class.' },
    ],
    relatedIntentPages: ['pdf-fill-api', 'pdf-fill-api-curl', 'api-fill-calculated-pdf', 'webhook-json-to-pdf-form'],
    relatedDocs: ['api-fill', 'troubleshooting', 'rename-mapping'],
  },
  {
    key: 'java-fill-pdf-api',
    path: '/java-fill-pdf-api',
    navLabel: 'Java PDF Fill API',
    heroTitle: 'Fill PDFs With Java Using a JSON-to-PDF API',
    heroSummary:
      'Call a DullyPDF template endpoint from Java or Spring Boot to fill existing PDF forms without maintaining PDF form logic in your service.',
    seoKeywords: ['java fill pdf api', 'fill pdf form java', 'java json to pdf form', 'spring boot fill pdf template', 'java populate pdf form'],
    valuePoints: ['Use Java for business logic and DullyPDF for fixed-template PDF output.', 'Avoid rebuilding checkbox, radio, appearance, and flattening behavior in every service.', 'Use one saved template schema across environments.'],
    proofPoints: ['API Fill is a standard HTTP endpoint.', 'DullyPDF stores template mapping and fill rules.', 'Generated PDFs can be flat or editable according to workflow needs.'],
    intentSummary: 'Java teams often compare PDFBox, iText, commercial SDKs, or hosted APIs for form filling.',
    fitSummary: 'DullyPDF fits when a hosted template endpoint is simpler than owning PDF internals in Java.',
    setupSummary: 'Publish the DullyPDF endpoint, then call it from `java.net.http.HttpClient`, Spring WebClient, or another approved HTTP client.',
    setupBullets: ['Keep secrets in environment or secret storage.', 'Serialize the top-level `data` object deliberately.', 'Store generated PDFs after validating them.'],
    mappingSummary: 'Map domain DTOs to DullyPDF schema keys rather than leaking internal object names directly to the PDF layer.',
    mappingBullets: ['Convert enums to expected radio or checkbox options.', 'Omit calculated outputs from caller input unless the schema expects them.', 'Use flat output for final records.'],
    qaSummary: 'Add a fixture request in staging so template changes do not break Java-side generation silently.',
    boundary: 'This page should compare tradeoffs without dismissing Java PDF libraries that are valid for lower-level use cases.',
    faqs: [
      { question: 'Can Java fill a PDF through DullyPDF?', answer: 'Yes. Java can post JSON to API Fill and handle the returned PDF bytes.' },
      { question: 'Is a Java SDK required?', answer: 'No. A standard HTTP client is enough because the API is HTTPS and JSON.' },
      { question: 'Can Spring Boot stream the PDF to a browser?', answer: 'Yes. After the API call returns PDF bytes, the app can stream or store them normally.' },
    ],
    relatedIntentPages: ['pdf-fill-api', 'webhook-json-to-pdf-form', 'one-json-fill-multiple-pdfs', 'api-fill-calculated-pdf'],
    relatedDocs: ['api-fill', 'troubleshooting', 'rename-mapping'],
  },
  {
    key: 'csharp-fill-pdf-api',
    path: '/csharp-fill-pdf-api',
    navLabel: 'C# PDF Fill API',
    heroTitle: 'Fill PDFs With C# and .NET Using a JSON-to-PDF API',
    heroSummary:
      'Use C# or ASP.NET Core to send JSON to a DullyPDF saved template endpoint and receive a generated PDF response.',
    seoKeywords: ['c# fill pdf api', 'dotnet fill pdf form', 'asp.net fill pdf template', 'csharp json to pdf form', '.net populate pdf form'],
    valuePoints: ['Keep .NET services focused on data and orchestration.', 'Use DullyPDF for template setup, schema, and PDF materialization.', 'Return or store final PDFs without PDF field library edge cases in the app.'],
    proofPoints: ['API Fill is a normal JSON-over-HTTPS call.', 'DullyPDF supports strict request-envelope validation.', 'Owner endpoints expose schema and audit activity.'],
    intentSummary: '.NET teams need reliable PDF output from application records, CRM data, or Microsoft workflow data.',
    fitSummary: 'DullyPDF fits when the app can call an endpoint instead of manipulating AcroForms directly.',
    setupSummary: 'Publish the template endpoint and call it from `HttpClient` in a controller, worker, or background job.',
    setupBullets: ['Use configuration or secret stores for endpoint keys.', 'Set JSON content type explicitly.', 'Stream the PDF response or upload it to blob storage.'],
    mappingSummary: 'Map C# models to DullyPDF field keys and keep PDF-specific field names out of deeper domain code where possible.',
    mappingBullets: ['Normalize nullable values.', 'Match radio and checkbox values to the published schema.', 'Use group API endpoints for multi-PDF output.'],
    qaSummary: 'Keep a representative payload fixture so template and code changes can be checked together.',
    boundary: 'Do not claim a NuGet client package unless one exists. HTTP examples are enough.',
    faqs: [
      { question: 'Can C# fill a PDF with DullyPDF?', answer: 'Yes. C# can call API Fill with JSON and receive PDF bytes.' },
      { question: 'Does this work with ASP.NET Core?', answer: 'Yes. Use `HttpClient` from a controller, service, or background worker.' },
      { question: 'Can .NET generate a packet ZIP?', answer: 'Yes, when calling a DullyPDF group API endpoint.' },
    ],
    relatedIntentPages: ['pdf-fill-api', 'power-automate-fill-pdf-template', 'api-fill-calculated-pdf', 'one-json-fill-multiple-pdfs'],
    relatedDocs: ['api-fill', 'troubleshooting', 'rename-mapping'],
  },
  {
    key: 'go-fill-pdf-api',
    path: '/go-fill-pdf-api',
    navLabel: 'Go PDF Fill API',
    heroTitle: 'Fill PDFs With Go Using a JSON-to-PDF API',
    heroSummary:
      'Use Go `net/http` to post JSON to a DullyPDF template endpoint and stream the filled PDF response without shipping PDF binaries.',
    seoKeywords: ['go fill pdf api', 'golang fill pdf form', 'go json to pdf form', 'golang pdf template api', 'go populate pdf'],
    valuePoints: ['Keep Go services small and dependency-light.', 'Use DullyPDF for PDF template materialization.', 'Deploy in Cloud Run, Lambda, workers, or long-running services without native PDF tooling.'],
    proofPoints: ['API Fill is HTTPS and JSON.', 'The endpoint returns generated PDF bytes.', 'Template schemas keep caller payloads stable.'],
    intentSummary: 'Go developers usually want a small service boundary and may not want PDF manipulation libraries in the binary.',
    fitSummary: 'DullyPDF fits when Go owns the source record and DullyPDF owns the existing PDF template.',
    setupSummary: 'Use Go to marshal the `data` payload, set Basic auth, send the request, and stream the response to storage or the caller.',
    setupBullets: ['Keep timeout handling explicit.', 'Log non-2xx responses with request context.', 'Use fixtures for repeatable output checks.'],
    mappingSummary: 'Map Go structs to DullyPDF schema keys at the API boundary.',
    mappingBullets: ['Use string values for date-like fields unless the schema expects another type.', 'Normalize enum values before sending.', 'Keep binary file handling separate from JSON fill payloads.'],
    qaSummary: 'Run fixture payloads in staging after any template update so Go-side code and template schema stay aligned.',
    boundary: 'Keep examples standard-library first and avoid implying a Go SDK unless it exists.',
    faqs: [
      { question: 'Can Go fill a PDF through an API?', answer: 'Yes. Go can post JSON to DullyPDF API Fill and receive a PDF response.' },
      { question: 'Do I need a PDF library in my Go service?', answer: 'No. The Go service can treat DullyPDF as the PDF template endpoint.' },
      { question: 'Can this run on Cloud Run or Lambda?', answer: 'Yes. It is just an outbound HTTPS request from your service.' },
    ],
    relatedIntentPages: ['pdf-fill-api-curl', 'webhook-json-to-pdf-form', 'pdf-fill-api', 'one-json-fill-multiple-pdfs'],
    relatedDocs: ['api-fill', 'troubleshooting', 'rename-mapping'],
  },
  {
    key: 'ruby-fill-pdf-api',
    path: '/ruby-fill-pdf-api',
    navLabel: 'Ruby PDF Fill API',
    heroTitle: 'Fill PDFs With Ruby or Rails Using a JSON-to-PDF API',
    heroSummary:
      'Call DullyPDF API Fill from Ruby or Rails to turn application records into existing filled PDF templates.',
    seoKeywords: ['ruby fill pdf api', 'rails fill pdf form', 'ruby json to pdf form', 'rails pdf template api', 'ruby populate pdf'],
    valuePoints: ['Use Rails for records and DullyPDF for fixed-template output.', 'Avoid maintaining low-level PDF field code in the app.', 'Attach generated PDFs to Active Storage, email, or downstream workflows.'],
    proofPoints: ['API Fill is HTTP and JSON.', 'Saved templates expose stable schemas.', 'Flat output keeps final PDFs viewer-friendly.'],
    intentSummary: 'Rails apps often need PDFs from customer, order, application, or case records.',
    fitSummary: 'DullyPDF fits when the PDF layout is already fixed and the Rails app can send JSON.',
    setupSummary: 'Publish the template endpoint and call it from `Net::HTTP`, Faraday, a job, or a service object.',
    setupBullets: ['Keep endpoint keys in credentials or environment variables.', 'Build a small request object around the public schema.', 'Store or stream the returned PDF as a normal file.'],
    mappingSummary: 'Map ActiveRecord attributes to the DullyPDF schema and keep PDF-specific transformations in one boundary layer.',
    mappingBullets: ['Normalize booleans and enums.', 'Check long text fields in the final layout.', 'Use group API endpoints for packet ZIPs.'],
    qaSummary: 'Use one fixture record per template so PDF output can be reviewed after template changes.',
    boundary: 'Do not claim a Ruby gem. The practical path is an HTTP API call.',
    faqs: [
      { question: 'Can Ruby fill a PDF with DullyPDF?', answer: 'Yes. Ruby can send JSON to API Fill and save the returned PDF.' },
      { question: 'Can Rails attach the generated PDF?', answer: 'Yes. Rails can attach or email the PDF bytes after the API call returns.' },
      { question: 'Is this HTML-to-PDF?', answer: 'No. DullyPDF fills an existing PDF template from structured values.' },
    ],
    relatedIntentPages: ['pdf-fill-api', 'webhook-json-to-pdf-form', 'one-json-fill-multiple-pdfs', 'pdf-fill-api-curl'],
    relatedDocs: ['api-fill', 'troubleshooting', 'rename-mapping'],
  },
];

const workflowPages = [
  {
    key: 'turn-pdf-into-online-form',
    path: '/turn-pdf-into-online-form',
    navLabel: 'PDF to Online Form',
    heroTitle: 'Turn an Existing PDF Into an Online Form',
    heroSummary:
      'Convert a reviewed PDF template into a hosted respondent form so people submit answers online and DullyPDF generates the filled PDF later.',
    seoKeywords: ['turn pdf into online form', 'pdf to online form', 'convert pdf to web form', 'existing pdf to web form', 'online form that fills pdf'],
    valuePoints: ['Start from the PDF layout your team already uses.', 'Collect responses in a mobile-friendly web form.', 'Generate flat PDFs after submission instead of asking respondents to edit PDF fields.'],
    proofPoints: ['Fill By Link publishes hosted respondent forms from saved templates.', 'Owners can manage requiredness, text limits, custom questions, and responses.', 'Stored responses can feed Search & Fill and signing workflows.'],
    intentSummary: 'Many teams want respondents to answer questions online while the final record remains the existing PDF.',
    fitSummary: 'DullyPDF fits by turning reviewed PDF fields into a respondent-facing form backed by the saved template.',
    setupSummary: 'Detect and clean the PDF fields, save the template, then open Fill By Link to choose the public questions and settings.',
    setupBullets: ['Review field names before publishing.', 'Hide or exclude fields that should not be respondent-facing.', 'Preview the public form before sharing the link.'],
    mappingSummary: 'DullyPDF stores respondent answers as structured records tied to the template.',
    mappingBullets: ['Use required questions for fields needed in every output.', 'Use custom questions only when they support the workflow.', 'Use flat PDFs for respondent receipts and final records.'],
    qaSummary: 'Submit a test response, generate the PDF, and inspect the output before sending the link externally.',
    boundary: 'Do not describe this as a general form builder with every conditional logic feature. It is a PDF-backed respondent workflow.',
    faqs: [
      { question: 'Can DullyPDF turn a PDF into an online form?', answer: 'Yes. Fill By Link publishes a hosted form from a saved PDF template.' },
      { question: 'Do respondents edit the PDF directly?', answer: 'No. Respondents fill a web form, and DullyPDF generates the PDF from their answers.' },
      { question: 'Can I review responses before generating PDFs?', answer: 'Yes. Owners can review stored responses and use them in the workspace workflow.' },
    ],
    relatedIntentPages: ['fill-pdf-by-link', 'pdf-to-fillable-form', 'respondent-download-filled-pdf', 'online-form-to-signed-pdf'],
    relatedDocs: ['fill-by-link', 'getting-started', 'editor-workflow'],
  },
  {
    key: 'one-web-form-fill-multiple-pdfs',
    path: '/one-web-form-fill-multiple-pdfs',
    navLabel: 'One Web Form Multiple PDFs',
    heroTitle: 'One Web Form That Fills Multiple PDFs',
    heroSummary:
      'Use saved template groups to collect one respondent record and fill a packet of related PDFs without retyping shared answers.',
    seoKeywords: ['one web form fill multiple pdfs', 'single form multiple pdfs', 'one intake form fill pdf packet', 'web form to multiple pdfs', 'fill multiple pdfs from one form'],
    valuePoints: ['Collect shared respondent data once.', 'Fill each saved PDF template in a packet from the same record.', 'Use groups when multiple documents belong to one repeat workflow.'],
    proofPoints: ['DullyPDF groups saved templates into packets.', 'Group Fill By Link publishes one merged respondent form.', 'Group API Fill can return a ZIP of generated PDFs.'],
    intentSummary: 'Packet workflows often ask for the same name, address, ID, policy, or application fields across several PDFs.',
    fitSummary: 'DullyPDF fits when each packet document remains its own fixed template but shares one respondent or record.',
    setupSummary: 'Save each template, add them to a group, review shared field names, then publish a group Fill By Link or group API endpoint.',
    setupBullets: ['Use consistent field names across documents.', 'Review duplicate respondent-facing questions.', 'Republish group links after membership changes.'],
    mappingSummary: 'Shared source fields should fill every matching template field while document-specific fields remain explicit.',
    mappingBullets: ['Test one full packet before broad sharing.', 'Use group Rename + Map for cleaner shared schemas.', 'Use flat output for external packet delivery.'],
    qaSummary: 'Generate the whole packet from a test response and inspect every document, not just the first PDF.',
    boundary: 'This is fixed-template packet filling. It is not variable-length document assembly.',
    faqs: [
      { question: 'Can one web form fill several PDFs?', answer: 'Yes. A DullyPDF group Fill By Link can collect one merged response for a saved template group.' },
      { question: 'What happens if the group changes?', answer: 'Group membership changes should trigger review and republishing so the public form matches the packet.' },
      { question: 'Can this work through an API too?', answer: 'Yes. Group API Fill can generate a packet ZIP from one JSON record.' },
    ],
    relatedIntentPages: ['pdf-packet-workflow', 'batch-fill-pdf-forms', 'fill-pdf-by-link', 'one-json-fill-multiple-pdfs'],
    relatedDocs: ['create-group', 'fill-by-link', 'api-fill'],
  },
  {
    key: 'one-json-fill-multiple-pdfs',
    path: '/one-json-fill-multiple-pdfs',
    navLabel: 'One JSON Multiple PDFs',
    heroTitle: 'Fill Multiple PDF Templates From One JSON Payload',
    heroSummary:
      'Use DullyPDF group API Fill to send one structured JSON record and receive a ZIP packet of filled PDFs.',
    seoKeywords: ['one json fill multiple pdfs', 'json to pdf packet', 'fill multiple pdfs from json', 'pdf packet api', 'generate multiple pdfs from one record'],
    valuePoints: ['Send one payload for a repeat PDF packet.', 'Keep each PDF as a reviewed saved template.', 'Return a ZIP for downstream storage, email, or review.'],
    proofPoints: ['Saved groups organize related templates.', 'Group API Fill is designed for packet workflows.', 'Template schemas expose expected field names and rules.'],
    intentSummary: 'Developers and operations teams often need one record to generate several related PDFs.',
    fitSummary: 'DullyPDF fits when packet documents share data but remain separate fixed templates.',
    setupSummary: 'Prepare and save each template, create a group, verify shared naming, then publish the group endpoint.',
    setupBullets: ['Use one canonical schema for shared identity fields.', 'Keep document-specific keys documented.', 'Test with the largest realistic packet.'],
    mappingSummary: 'The JSON payload should contain the shared fields and any per-document values needed by the group templates.',
    mappingBullets: ['Avoid conflicting normalized field names.', 'Let calculated fields compute during materialization.', 'Do not include signature widgets in generic API payloads.'],
    qaSummary: 'Unzip the packet, inspect each generated PDF, and compare values against the source JSON before using the endpoint in production.',
    boundary: 'This is group template generation, not arbitrary document assembly or looping table generation.',
    faqs: [
      { question: 'Can one JSON payload fill multiple PDFs?', answer: 'Yes. DullyPDF group API Fill can generate a packet ZIP from one payload.' },
      { question: 'Do all PDFs need the same fields?', answer: 'No. Shared fields can repeat across templates, and each template can also have document-specific fields.' },
      { question: 'Can calculated fields be included?', answer: 'Source number inputs can be sent, and DullyPDF computes calculated outputs during materialization.' },
    ],
    relatedIntentPages: ['pdf-packet-workflow', 'batch-fill-pdf-forms', 'pdf-fill-api', 'webhook-json-to-pdf-form'],
    relatedDocs: ['create-group', 'api-fill', 'rename-mapping'],
  },
  {
    key: 'respondent-download-filled-pdf',
    path: '/respondent-download-filled-pdf',
    navLabel: 'Respondent PDF Download',
    heroTitle: 'Let Respondents Download a Filled PDF After Submitting a Web Form',
    heroSummary:
      'Publish a DullyPDF Fill By Link that collects answers and can expose a respondent copy of the completed PDF when the workflow supports it.',
    seoKeywords: ['respondent download filled pdf', 'form submission download pdf', 'web form respondent pdf copy', 'filled pdf after submit', 'online form download pdf'],
    valuePoints: ['Give respondents a PDF copy without asking them to edit the PDF directly.', 'Use flat output for receipt-style downloads.', 'Keep owner review and signing workflows separate when needed.'],
    proofPoints: ['Template Fill By Link supports respondent PDF download options.', 'Flat downloads bake values into page content.', 'Signing artifacts follow a stricter immutable path.'],
    intentSummary: 'Some workflows need a person to submit answers online and leave with their own completed PDF copy.',
    fitSummary: 'DullyPDF fits when the form is based on a saved template and the respondent copy should display reliably.',
    setupSummary: 'Publish a template Fill By Link, choose respondent download settings, and test the public submission flow.',
    setupBullets: ['Use flat output unless the respondent truly needs live fields.', 'Keep required questions aligned with PDF output needs.', 'Preview the completed PDF before sharing the link.'],
    mappingSummary: 'Respondent answers become source values for the saved template and the generated copy.',
    mappingBullets: ['Avoid leaving stale saved field values in the template.', 'Use clear question labels for respondent-facing fields.', 'Separate signing downloads from ordinary respondent copies.'],
    qaSummary: 'Submit a test response as a respondent and inspect the download in a browser, Acrobat, and a mobile viewer if recipients use mobile.',
    boundary: 'Do not claim every group or signing path supports the same public download mode. Keep the page tied to supported Fill By Link template behavior.',
    faqs: [
      { question: 'Can respondents download their filled PDF?', answer: 'Supported template Fill By Link workflows can expose respondent PDF downloads.' },
      { question: 'Should respondent downloads be flat or editable?', answer: 'Flat is usually better because the values display as page content across viewers.' },
      { question: 'Is this the same as a signed PDF download?', answer: 'No. Signing workflows use separate immutable source and audit artifact handling.' },
    ],
    relatedIntentPages: ['fill-pdf-by-link', 'flat-vs-editable-pdf', 'turn-pdf-into-online-form', 'online-form-to-signed-pdf'],
    relatedDocs: ['fill-by-link', 'save-download-profile', 'signature-workflow'],
  },
  {
    key: 'online-form-to-signed-pdf',
    path: '/online-form-to-signed-pdf',
    navLabel: 'Online Form to Signed PDF',
    heroTitle: 'Collect a Web Form Response and Send the Filled PDF for Signature',
    heroSummary:
      'Use Fill By Link plus post-submit signing to collect answers first, materialize the filled PDF, and route the exact record into signing.',
    seoKeywords: ['online form to signed pdf', 'web form to signed pdf', 'form submission to signed pdf', 'fill and sign pdf from web form', 'collect answers then sign pdf'],
    valuePoints: ['Separate respondent data collection from signing ceremony steps.', 'Freeze the filled PDF before signing.', 'Retain audit artifacts and validation evidence for completed requests.'],
    proofPoints: ['Fill By Link can hand a stored response into signing when configured.', 'Signing uses immutable source artifacts and audit receipts.', 'Public validation pages can verify completed signing records.'],
    intentSummary: 'Many signature workflows start with data collection, not with an already completed PDF.',
    fitSummary: 'DullyPDF fits when the respondent answers should fill the template before the signing request is created.',
    setupSummary: 'Prepare the saved template, publish Fill By Link, enable post-submit signing, map signer name/email questions, and test the handoff.',
    setupBullets: ['Confirm the document category is supported.', 'Map visible signer identity questions.', 'Review consumer or company-binding disclosures when applicable.'],
    mappingSummary: 'The submitted response fills the PDF, then the signing flow uses that materialized record as the source.',
    mappingBullets: ['Use flat source artifacts for signing.', 'Keep respondent downloads flat when signing is enabled.', 'Verify signing state from the owner responses view.'],
    qaSummary: 'Run a full test from response submission through email invite, signing completion, signed PDF, audit receipt, and validation page.',
    boundary: 'Do not make blanket legal-validity claims. The page should describe DullyPDF workflow evidence and supported-document guardrails.',
    faqs: [
      { question: 'Can a web form response become a signed PDF?', answer: 'Yes. DullyPDF can collect answers through Fill By Link and route the materialized PDF into signing when configured.' },
      { question: 'Does the signer edit the PDF directly?', answer: 'No. The signer reviews the frozen source record and completes the signing ceremony.' },
      { question: 'Is every document type supported?', answer: 'No. DullyPDF signing has documented category guardrails and is not blanket legal advice.' },
    ],
    relatedIntentPages: ['fill-pdf-link-signature', 'pdf-signature-workflow', 'pdf-signature-audit-trail', 'turn-pdf-into-online-form'],
    relatedDocs: ['signature-workflow', 'fill-by-link', 'troubleshooting'],
  },
  {
    key: 'excel-to-fillable-pdf-template',
    path: '/excel-to-fillable-pdf-template',
    navLabel: 'Excel to Fillable PDF',
    heroTitle: 'Fill a Reusable PDF Template From Excel Rows',
    heroSummary:
      'Upload XLSX rows, search for the right record, and fill a reviewed DullyPDF template without converting Excel data by hand.',
    seoKeywords: ['excel to fillable pdf template', 'fill pdf from excel', 'excel rows to pdf form', 'xlsx to fillable pdf', 'populate pdf from excel'],
    valuePoints: ['Use Excel files directly in Search & Fill.', 'Keep the PDF template reusable after the first setup pass.', 'Test edge-case rows before bulk or repeat output.'],
    proofPoints: ['Search & Fill supports XLSX rows.', 'DullyPDF preserves saved template mappings.', 'Date and checkbox handling can be reviewed before output.'],
    intentSummary: 'Many users search for Excel specifically even when the broader workflow is spreadsheet-to-PDF filling.',
    fitSummary: 'DullyPDF fits when an Excel row should populate a fixed PDF form.',
    setupSummary: 'Clean the worksheet headers, upload the XLSX as the source file, and map columns to the saved template fields.',
    setupBullets: ['Use one header row.', 'Avoid merged headers and hidden meaning in formatting.', 'Keep formula outputs as values if they are the fields you intend to fill.'],
    mappingSummary: 'Search & Fill reads row values and writes matching values into the active template fields.',
    mappingBullets: ['Check spreadsheet date auto-formatting.', 'Use clear yes/no values for checkboxes.', 'Test long text values for field overflow.'],
    qaSummary: 'Choose a row with realistic edge cases and inspect the filled PDF before saving or downloading final outputs.',
    boundary: 'This page should stay distinct from generic CSV coverage by addressing Excel-specific header, date, and worksheet behavior.',
    faqs: [
      { question: 'Can DullyPDF fill PDFs from Excel files?', answer: 'Yes. Search & Fill supports XLSX source rows.' },
      { question: 'Do I need to convert Excel to CSV first?', answer: 'No. CSV is supported, but XLSX can be used directly.' },
      { question: 'What causes Excel-to-PDF fill mistakes?', answer: 'Duplicate headers, date formatting, ambiguous checkbox values, and unreviewed field names are common causes.' },
    ],
    relatedIntentPages: ['fill-pdf-from-csv', 'fill-pdf-from-google-sheets', 'microsoft-forms-to-filled-pdf', 'pdf-date-format-csv-fill'],
  },
  {
    key: 'sql-database-to-pdf-form-api',
    path: '/sql-database-to-pdf-form-api',
    navLabel: 'SQL Database to PDF',
    heroTitle: 'Fill PDF Forms From SQL Database Records',
    heroSummary:
      'Map PDF fields to database-style schemas, then fill saved templates from exported rows or JSON produced by your application backend.',
    seoKeywords: ['sql database to pdf form', 'database record to pdf form', 'fill pdf from sql database', 'sql to pdf template', 'database to fillable pdf api'],
    valuePoints: ['Use SQL definitions for schema mapping when preparing templates.', 'Use application JSON or exported rows for actual record filling.', 'Publish API endpoints for backend-driven PDF generation.'],
    proofPoints: ['DullyPDF supports SQL files as schema-only sources.', 'Search & Fill supports CSV/XLSX/JSON rows.', 'API Fill accepts JSON from your database-backed application.'],
    intentSummary: 'Database-backed teams want PDFs generated from records without copy-paste.',
    fitSummary: 'DullyPDF fits when database columns can be mapped to stable PDF fields.',
    setupSummary: 'Use SQL schema definitions to help align field names, then decide whether operators will fill from row exports or the backend will call API Fill.',
    setupBullets: ['Keep database field names stable.', 'Create a saved template before wiring API calls.', 'Use one fixture record for template QA.'],
    mappingSummary: 'Actual record filling should use CSV/XLSX/JSON rows or API JSON, not raw SQL files.',
    mappingBullets: ['Map nullable values explicitly.', 'Convert database enums to checkbox or radio values.', 'Keep calculated outputs out of caller-required input when DullyPDF computes them.'],
    qaSummary: 'Generate PDFs from a staging record that exercises required, optional, checkbox, radio, date, and calculated fields.',
    boundary: 'SQL uploads are schema-only in DullyPDF today. Do not claim direct SQL row execution or database connections.',
    faqs: [
      { question: 'Can DullyPDF fill PDFs directly from SQL?', answer: 'SQL files are schema-only. Fill records through CSV/XLSX/JSON rows or API Fill from your backend.' },
      { question: 'Can database columns map to PDF fields?', answer: 'Yes. Schema mapping can align database-style headers with reviewed PDF field names.' },
      { question: 'When should I use API Fill?', answer: 'Use API Fill when your application already reads the database record and can send JSON.' },
    ],
    relatedIntentPages: ['pdf-to-database-template', 'pdf-fill-api', 'webhook-json-to-pdf-form', 'fill-pdf-from-csv'],
    relatedDocs: ['rename-mapping', 'api-fill', 'search-fill'],
  },
];

const supportPages = [
  {
    key: 'flatten-filled-pdf-form',
    path: '/flatten-filled-pdf-form',
    navLabel: 'Flatten Filled PDF',
    heroTitle: 'Flatten a Filled PDF Form for Sharing',
    heroSummary:
      'Generate flat filled PDFs so completed values are baked into page content instead of relying on editable fields in the recipient viewer.',
    seoKeywords: ['flatten filled pdf form', 'flatten pdf form after filling', 'make filled pdf flat', 'flatten fillable pdf online', 'pdf form flattening'],
    valuePoints: ['Use flat output for final records, filings, receipts, and external sharing.', 'Avoid viewer-specific editable field display problems.', 'Keep editable output only when the next person must continue editing fields.'],
    proofPoints: ['DullyPDF supports flat and editable download modes.', 'Fill By Link recommends flat respondent copies.', 'Signing source artifacts are frozen as non-editable PDFs.'],
    intentSummary: 'Users search for flattening when completed PDF fields disappear, remain editable, or fail in browser/mobile viewers.',
    fitSummary: 'DullyPDF fits by materializing the PDF as flat page content after fields are filled.',
    setupSummary: 'Fill the reviewed template first, choose flat output for sharing, and verify the generated PDF displays values without live field interaction.',
    setupBullets: ['Use editable only for continued field editing.', 'Use flat for final records and recipients.', 'Recheck calculated values before output.'],
    mappingSummary: 'Flattening is an output decision after the correct source values have been filled.',
    mappingBullets: ['Do not use flattening to hide bad mapping.', 'Check checkbox and radio selections before download.', 'Keep a saved template for future editable changes.'],
    qaSummary: 'Open the flat PDF in a browser and Acrobat to confirm values appear as page content.',
    boundary: 'Flattening helps display reliability and casual edit prevention, but it is not DRM or a complete document security model.',
    faqs: [
      { question: 'Can DullyPDF flatten a filled PDF?', answer: 'Yes. Flat downloads bake completed values into the PDF page content.' },
      { question: 'When should I use editable output?', answer: 'Use editable output only when another person needs to keep working with live PDF fields.' },
      { question: 'Does flattening make a PDF impossible to change?', answer: 'No. It reduces editable form fields, but it is not a complete security guarantee.' },
    ],
    relatedIntentPages: ['flat-vs-editable-pdf', 'make-pdf-read-only-after-filling', 'filled-pdf-fields-not-showing', 'pdf-signature-audit-trail'],
    relatedDocs: ['save-download-profile', 'troubleshooting', 'fill-by-link'],
  },
  {
    key: 'filled-pdf-fields-not-showing',
    path: '/filled-pdf-fields-not-showing',
    navLabel: 'PDF Fields Not Showing',
    heroTitle: 'Filled PDF Fields Not Showing? Why It Happens',
    heroSummary:
      'Understand why filled PDF values can appear blank in some viewers and when flat DullyPDF output is the safer final-record choice.',
    seoKeywords: ['filled pdf fields not showing', 'pdf form fields appear blank', 'filled pdf blank in chrome', 'pdf values disappear after saving', 'pdf form text not visible'],
    valuePoints: ['Diagnose viewer differences before resending documents.', 'Use flat output when recipients only need the final record.', 'Use editable output when live field editing must continue.'],
    proofPoints: ['DullyPDF handles AcroForm appearance and flat materialization paths.', 'Usage docs recommend flat outputs for external recipients.', 'AcroForm appearance docs cover `/V`, `/DA`, and `/AP` behavior.'],
    intentSummary: 'This search usually comes from a filled PDF that looks right in one viewer and wrong in another.',
    fitSummary: 'DullyPDF fits by explaining the PDF field model and offering flat output for final sharing.',
    setupSummary: 'Check whether the file is intended to stay editable or become a final record, then choose the matching DullyPDF output mode.',
    setupBullets: ['Open the file in Acrobat and a browser viewer.', 'Confirm values are present in fields, not just drawn overlays.', 'Use flat output for final recipient copies.'],
    mappingSummary: 'Field values, appearance streams, and viewer rendering rules can disagree even when the field data exists.',
    mappingBullets: ['Review text fields and checkboxes separately.', 'Avoid relying on email-preview PDFs for QA.', 'Regenerate flat output when viewers disagree.'],
    qaSummary: 'If the recipient does not need live fields, send a flat PDF and keep the saved template for future edits.',
    boundary: 'Keep this as practical troubleshooting, not a deep PDF implementation reference.',
    faqs: [
      { question: 'Why do filled PDF fields look blank?', answer: 'Some viewers do not render editable field appearances the same way, especially when appearance streams or defaults are stale.' },
      { question: 'What is the safest output for recipients?', answer: 'A flat PDF is usually safest because the values are drawn into page content.' },
      { question: 'Should I still keep an editable copy?', answer: 'Keep the DullyPDF template or editable output when someone must continue editing fields later.' },
    ],
    relatedIntentPages: ['acroform-field-appearance', 'flat-vs-editable-pdf', 'flatten-filled-pdf-form', 'pdf-form-calculations-not-working'],
    relatedDocs: ['troubleshooting', 'save-download-profile', 'editor-workflow'],
  },
  {
    key: 'make-pdf-read-only-after-filling',
    path: '/make-pdf-read-only-after-filling',
    navLabel: 'Make PDF Read-Only',
    heroTitle: 'Make a PDF Read-Only After Filling It',
    heroSummary:
      'Use flat output when a completed PDF should behave like a final record instead of an editable form.',
    seoKeywords: ['make pdf read only after filling', 'lock filled pdf form', 'make fillable pdf non editable', 'filled pdf read only', 'protect filled pdf form'],
    valuePoints: ['Choose final-record output deliberately.', 'Use flat PDFs for external recipients and archives.', 'Keep editable PDFs only for workflows that require continued field changes.'],
    proofPoints: ['DullyPDF download modes include flat and editable PDFs.', 'Flat output is recommended for Fill By Link respondent receipts.', 'Signing workflows freeze reviewed records before completion.'],
    intentSummary: 'Users often say "read-only" when they want recipients to see completed values without editing live fields.',
    fitSummary: 'DullyPDF fits by creating a flat completed PDF after the source values are reviewed.',
    setupSummary: 'Fill and inspect the template, then select flat output for the completed copy.',
    setupBullets: ['Review values before flattening.', 'Use editable output for internal revision workflows.', 'Use signing workflows when signature evidence is required.'],
    mappingSummary: 'Read-only behavior is separate from field mapping. Fix mapping first, then choose output mode.',
    mappingBullets: ['Check required fields are filled.', 'Check checkbox/radio selections.', 'Open the final PDF in the viewers recipients use.'],
    qaSummary: 'Treat the flat PDF as the copy to send, while retaining the saved template for future runs.',
    boundary: 'Do not imply flat output is the same as encryption, permissions enforcement, or irreversible security.',
    faqs: [
      { question: 'Can DullyPDF make a filled PDF non-editable?', answer: 'DullyPDF can generate a flat PDF where completed values are baked into page content.' },
      { question: 'Is flat output the same as password protection?', answer: 'No. Flat output removes live form fields from the completed copy but is not full document security.' },
      { question: 'Can I still edit the template later?', answer: 'Yes. Keep the saved DullyPDF template for future edits and repeat fills.' },
    ],
    relatedIntentPages: ['flatten-filled-pdf-form', 'flat-vs-editable-pdf', 'pdf-signature-audit-trail', 'filled-pdf-fields-not-showing'],
    relatedDocs: ['save-download-profile', 'troubleshooting', 'signature-workflow'],
  },
  {
    key: 'pdf-checkbox-values-csv',
    path: '/pdf-checkbox-values-csv',
    navLabel: 'PDF Checkbox CSV Values',
    heroTitle: 'Map CSV Values to PDF Checkboxes Correctly',
    heroSummary:
      'Use explicit checkbox rules and reviewed source values so CSV, Excel, JSON, or API data checks the right PDF options.',
    seoKeywords: ['pdf checkbox values csv', 'fill pdf checkbox from csv', 'pdf checkbox yes no values', 'map csv to pdf checkboxes', 'checkbox pdf automation'],
    valuePoints: ['Avoid checkbox ambiguity before filling real records.', 'Review boolean, enum, presence, and list-style rules.', 'Use one test row that exercises every option.'],
    proofPoints: ['DullyPDF stores checkbox group and option metadata.', 'Schema mapping can produce deterministic fill rules.', 'Search & Fill uses normalized values during fill.'],
    intentSummary: 'Checkbox failures are common when source values are vague or the PDF has several boxes with similar labels.',
    fitSummary: 'DullyPDF fits by making checkbox mapping part of template review, not a blind fill step.',
    setupSummary: 'Review checkbox groups after detection and before Search & Fill, Fill By Link, or API publication.',
    setupBullets: ['Name groups clearly.', 'Name option keys after source values.', 'Use representative rows with checked and unchecked examples.'],
    mappingSummary: 'Choose whether each checkbox behaves like a boolean, enum, presence signal, or list option.',
    mappingBullets: ['Use yes/no or true/false for boolean fields.', 'Use exact option values for radio-like checkbox groups.', 'Use separators consistently for multi-value lists.'],
    qaSummary: 'Clear and refill the PDF with a row that should check multiple different boxes so mistakes are visible.',
    boundary: 'Do not claim every unusual checkbox layout can be inferred perfectly without review.',
    faqs: [
      { question: 'What values should CSV use for PDF checkboxes?', answer: 'Use consistent values such as yes/no, true/false, or explicit option names that match the reviewed rule.' },
      { question: 'Why did the wrong checkbox fill?', answer: 'The source value may not match the group or option rule. Review mapping and checkbox metadata.' },
      { question: 'Can API Fill handle checkbox values?', answer: 'Yes, when the JSON values match the published schema and checkbox rules.' },
    ],
    relatedIntentPages: ['pdf-checkbox-automation', 'fill-pdf-from-csv', 'search-fill-pdf-review', 'pdf-radio-button-values-json'],
    relatedDocs: ['rename-mapping', 'search-fill', 'troubleshooting'],
  },
  {
    key: 'pdf-radio-button-values-json',
    path: '/pdf-radio-button-values-json',
    navLabel: 'PDF Radio JSON Values',
    heroTitle: 'Fill PDF Radio Buttons From JSON or CSV Values',
    heroSummary:
      'Treat PDF radio groups as single-select fields and map JSON, CSV, or Excel values to one reviewed option at a time.',
    seoKeywords: ['pdf radio button values json', 'fill pdf radio button json', 'pdf radio button csv', 'map radio buttons pdf form', 'pdf radio button automation'],
    valuePoints: ['Keep radio groups separate from checkbox logic.', 'Use one source value for the selected option.', 'Review option names before API or spreadsheet fills.'],
    proofPoints: ['DullyPDF treats radio fields as first-class single-select groups.', 'API schemas can expose group expectations.', 'The editor supports radio group review and cleanup.'],
    intentSummary: 'Radio buttons often fail when users model every option as a separate boolean.',
    fitSummary: 'DullyPDF fits by making the radio group a single field with one selected value.',
    setupSummary: 'Review the radio group in the editor and confirm each option has a meaningful expected value.',
    setupBullets: ['Use one field key for the group.', 'Use option values that match source enums.', 'Test every possible option before publishing.'],
    mappingSummary: 'Send a single JSON or CSV value that selects one option in the group.',
    mappingBullets: ['Do not send several true/false flags for one radio group.', 'Normalize capitalization and punctuation.', 'Keep checkbox pages separate from radio troubleshooting.'],
    qaSummary: 'Fill the PDF with one row per radio option during setup so every selection path is verified.',
    boundary: 'Do not blur radio buttons and checkboxes. Their data models are different.',
    faqs: [
      { question: 'How should JSON fill a PDF radio group?', answer: 'Send one value for the radio group field, matching one allowed option.' },
      { question: 'Why did my radio group stay blank?', answer: 'The source value may not match any reviewed option value.' },
      { question: 'Are radio buttons the same as checkboxes?', answer: 'No. Radio groups are single-select; checkboxes can represent booleans, enums, presence, or lists.' },
    ],
    relatedIntentPages: ['pdf-radio-button-editor', 'pdf-fill-api', 'fill-pdf-from-csv', 'pdf-checkbox-values-csv'],
    relatedDocs: ['editor-workflow', 'rename-mapping', 'api-fill'],
  },
  {
    key: 'pdf-date-format-csv-fill',
    path: '/pdf-date-format-csv-fill',
    navLabel: 'PDF Date CSV Fill',
    heroTitle: 'Fix PDF Date Formatting When Filling From CSV',
    heroSummary:
      'Normalize spreadsheet date values before filling PDF date-like fields so output stays predictable across Search & Fill and API workflows.',
    seoKeywords: ['pdf date format csv fill', 'csv date to pdf form', 'fill pdf date from csv', 'spreadsheet date pdf form', 'pdf form date format'],
    valuePoints: ['Avoid spreadsheet date surprises before generating PDFs.', 'Use consistent date formats for mapping and output.', 'Test blank, edge, and real-world dates.'],
    proofPoints: ['Search & Fill normalizes accepted date-like text values.', 'DullyPDF troubleshooting docs cover invalid date behavior.', 'API Fill benefits from predictable JSON date strings.'],
    intentSummary: 'Dates break when spreadsheets auto-format values or teams mix slash, dash, locale, and blank formats.',
    fitSummary: 'DullyPDF fits by making date handling part of the fill QA loop.',
    setupSummary: 'Decide the source date format before uploading CSV/XLSX or sending API JSON.',
    setupBullets: ['Prefer explicit `YYYY-MM-DD` values when possible.', 'Keep blank dates blank instead of placeholder text.', 'Test impossible dates during QA.'],
    mappingSummary: 'Map date source columns to date-like PDF fields and check the visible output after fill.',
    mappingBullets: ['Do not rely on spreadsheet display formatting alone.', 'Check exported CSV text, not just the spreadsheet UI.', 'Use consistent timezone-free date strings for forms that only need dates.'],
    qaSummary: 'Fill a row with a normal date, blank date, and edge date before sharing the template.',
    boundary: 'Do not claim broad date math, locale inference, or time-zone logic unless the feature exists.',
    faqs: [
      { question: 'What date format should CSV use for DullyPDF?', answer: 'Use a consistent explicit date format such as `YYYY-MM-DD` when possible.' },
      { question: 'Why did my PDF date look wrong?', answer: 'The exported spreadsheet value may differ from the formatted cell shown in Excel or Sheets.' },
      { question: 'Can DullyPDF calculate dates?', answer: 'No broad date math should be claimed. Normalize source dates before fill.' },
    ],
    relatedIntentPages: ['fill-pdf-from-csv', 'search-fill-pdf-review', 'excel-to-fillable-pdf-template', 'filled-pdf-fields-not-showing'],
    relatedDocs: ['search-fill', 'troubleshooting', 'rename-mapping'],
  },
  {
    key: 'duplicate-pdf-field-names',
    path: '/duplicate-pdf-field-names',
    navLabel: 'Duplicate PDF Field Names',
    heroTitle: 'Fix Duplicate PDF Field Names Before Auto-Fill',
    heroSummary:
      'Clean up repeated, generic, or copied PDF field names before mapping templates to spreadsheets, databases, links, or API payloads.',
    seoKeywords: ['duplicate pdf field names', 'fix duplicate pdf fields', 'pdf form fields same name', 'rename duplicate pdf form fields', 'pdf field names auto fill'],
    valuePoints: ['Make every important field addressable before automation.', 'Use AI rename and schema mapping as a review accelerator.', 'Avoid API payload ambiguity caused by copied form fields.'],
    proofPoints: ['DullyPDF field renaming preserves original name context.', 'Schema mapping uses reviewed field names.', 'Saved templates preserve normalized names for repeat fill.'],
    intentSummary: 'Duplicate field names usually come from copied AcroForm fields or generic authoring-tool defaults.',
    fitSummary: 'DullyPDF fits because repeat filling depends on stable human-readable field names.',
    setupSummary: 'Run detection or import embedded fields, review duplicate names, and rename fields before mapping.',
    setupBullets: ['Use nearby label text to name fields.', 'Keep repeated packet fields consistent only when they should share values.', 'Separate fields that look similar but mean different things.'],
    mappingSummary: 'A source column or JSON key can only fill the right place if the PDF field model is unambiguous.',
    mappingBullets: ['Fix duplicates before API publication.', 'Review checkboxes and radio groups separately.', 'Save the cleaned template for repeat use.'],
    qaSummary: 'Fill one record and inspect every repeated label area to verify each value went to the intended field.',
    boundary: 'Do not imply AI can decide every business meaning perfectly. Human review remains required.',
    faqs: [
      { question: 'Why are duplicate PDF field names a problem?', answer: 'They make it unclear which source value should fill which visible location.' },
      { question: 'Can DullyPDF rename duplicate fields?', answer: 'Yes. You can rename fields manually and use AI rename as a review aid.' },
      { question: 'Should I fix names before mapping?', answer: 'Yes. Clean field names make Search & Fill, Fill By Link, and API Fill more reliable.' },
    ],
    relatedIntentPages: ['fillable-form-field-name', 'ai-pdf-field-renaming', 'pdf-to-database-template', 'pdf-field-detection-tool'],
    relatedDocs: ['rename-mapping', 'editor-workflow', 'troubleshooting'],
  },
  {
    key: 'pdf-template-versioning',
    path: '/pdf-template-versioning',
    navLabel: 'PDF Template Versioning',
    heroTitle: 'Version and QA Reusable PDF Templates When Forms Change',
    heroSummary:
      'Decide when to update, overwrite, or create a new DullyPDF template as source PDFs, schemas, links, and API snapshots evolve.',
    seoKeywords: ['pdf template versioning', 'reusable pdf template version control', 'update pdf form template', 'pdf form revision workflow', 'pdf template qa'],
    valuePoints: ['Keep repeat PDF workflows maintainable as forms change.', 'Avoid breaking links, API endpoints, and packet groups with unreviewed edits.', 'Use one QA loop before treating a revised template as production-ready.'],
    proofPoints: ['Saved templates preserve editor snapshots and metadata.', 'API and Fill By Link workflows depend on saved template snapshots.', 'Groups need review when membership or template fields change.'],
    intentSummary: 'Reusable PDF templates become operational assets, and assets need change control.',
    fitSummary: 'DullyPDF fits by preserving saved state while still requiring review when the source PDF changes.',
    setupSummary: 'Compare the old and new source PDF, decide whether geometry changed, then update mapping or create a new template accordingly.',
    setupBullets: ['Create a new template when page layout changes materially.', 'Remap when only schema names changed.', 'Republish links or endpoints after intentional template changes.'],
    mappingSummary: 'Version changes affect field geometry, names, fill rules, respondent questions, API schemas, and packet behavior.',
    mappingBullets: ['Run clear-and-refill tests after changes.', 'Check group links after membership edits.', 'Keep old exported records separate from new template revisions.'],
    qaSummary: 'Use a representative record to validate detection, mapping, fill output, download mode, links, API, and signing handoff before rollout.',
    boundary: 'Do not promise full historical version control if the product stores the current saved snapshot rather than a full revision graph.',
    faqs: [
      { question: 'When should I create a new PDF template?', answer: 'Create a new template when the source PDF layout or field geometry changes materially.' },
      { question: 'When is remapping enough?', answer: 'Remapping may be enough when the PDF layout is unchanged and only source schema names changed.' },
      { question: 'Do links and API endpoints need review after changes?', answer: 'Yes. Any published workflow that depends on a template should be retested after template changes.' },
    ],
    relatedIntentPages: ['save-reusable-pdf-template', 'pdf-packet-workflow', 'search-fill-pdf-review', 'pdf-to-fillable-form'],
    relatedDocs: ['save-download-profile', 'editor-workflow', 'troubleshooting'],
  },
];

export const HIGH_INTENT_OPPORTUNITY_PAGES = [
  ...sourceSystemPages,
  ...automationPages,
  ...developerPages,
  ...workflowPages,
  ...supportPages,
].map(buildOpportunityPage);
