-- Mock patient intake schema matching new_patient_forms_1915ccb015_mock.csv
-- Used for testing SQL schema import against the new_patient_forms PDF.

CREATE TABLE new_patient_forms (
  patient_name VARCHAR(200) NOT NULL,
  patient_birthdate DATE,
  patient_street_address VARCHAR(300),
  patient_city VARCHAR(100),
  patient_state CHAR(2),
  patient_zip VARCHAR(10),
  patient_home_phone VARCHAR(20),
  patient_work_phone VARCHAR(20),
  patient_email VARCHAR(200),
  i_sex_f BOOLEAN,
  i_sex_m BOOLEAN,
  i_marital_status_divorced BOOLEAN,
  i_marital_status_married BOOLEAN,
  i_marital_status_partnership BOOLEAN,
  i_marital_status_separated BOOLEAN,
  i_marital_status_single BOOLEAN,
  i_marital_status_widowed BOOLEAN,
  employer_name VARCHAR(200),
  employer_phone VARCHAR(20),
  employer_street_address VARCHAR(300),
  employer_city VARCHAR(100),
  employer_state CHAR(2),
  employer_zip VARCHAR(10),
  spouse_partner_parent_name VARCHAR(200),
  emergency_contact_name VARCHAR(200),
  emergency_contact_phone VARCHAR(20),
  referral_source VARCHAR(200),
  responsible_party_name VARCHAR(200),
  responsible_party_street_address VARCHAR(300),
  responsible_party_city VARCHAR(100),
  responsible_party_state CHAR(2),
  responsible_party_zip VARCHAR(10),
  responsible_party_phone VARCHAR(20),
  responsible_party_email VARCHAR(200),
  responsible_party_birthdate DATE,
  dental_insurance_company VARCHAR(200),
  dental_insurance_phone VARCHAR(20),
  dental_insurance_subscriber_ssn VARCHAR(11),
  dental_insurance_group_number VARCHAR(50),
  dental_insurance_id_number VARCHAR(50),
  dental_insurance_city VARCHAR(100),
  dental_insurance_street_address VARCHAR(300),
  dental_insurance_state CHAR(2),
  dental_insurance_zip VARCHAR(10),
  dental_insurance_deductible_amount INTEGER,
  dental_insurance_amount_used INTEGER,
  dental_insurance_annual_maximum_benefit INTEGER,
  dental_insurance_policy_holder_name VARCHAR(200),
  dental_insurance_employer_name VARCHAR(200),
  dental_insurance_employer_phone VARCHAR(20),
  dental_insurance_employer_street_address VARCHAR(300),
  dental_insurance_employer_city VARCHAR(100),
  dental_insurance_employer_state CHAR(2),
  dental_insurance_employer_zip VARCHAR(10),
  secondary_dental_insurance_company VARCHAR(200),
  secondary_dental_insurance_phone VARCHAR(20),
  secondary_dental_insurance_subscriber_ssn VARCHAR(11),
  secondary_dental_insurance_group_number VARCHAR(50),
  secondary_dental_insurance_id_number VARCHAR(50),
  secondary_dental_insurance_street_address VARCHAR(300),
  secondary_dental_insurance_city VARCHAR(100),
  secondary_dental_insurance_state CHAR(2),
  secondary_dental_insurance_zip VARCHAR(10),
  secondary_dental_insurance_deductible_amount INTEGER,
  secondary_dental_insurance_amount_used INTEGER,
  secondary_dental_insurance_annual_maximum_benefit INTEGER,
  secondary_dental_insurance_policy_holder_name VARCHAR(200),
  secondary_dental_insurance_employer_name VARCHAR(200),
  secondary_dental_insurance_employer_phone VARCHAR(20),
  secondary_dental_insurance_employer_street_address VARCHAR(300),
  secondary_dental_insurance_employer_city VARCHAR(100),
  secondary_dental_insurance_employer_state CHAR(2),
  secondary_dental_insurance_employer_zip VARCHAR(10),
  dental_history_reason_for_visit TEXT,
  dental_history_last_dental_care_date DATE,
  dental_history_last_dental_xrays_date DATE,
  dental_history_former_dentist_name VARCHAR(200),
  dental_history_former_dentist_phone VARCHAR(20),
  i_dental_problem_bad_breath BOOLEAN,
  i_dental_problem_loose_teeth_or_broken_fillings BOOLEAN,
  i_dental_problem_bleeding_gums BOOLEAN,
  i_dental_problem_periodontal_treatment BOOLEAN,
  i_dental_problem_clicking_or_popping_jaw BOOLEAN,
  i_dental_problem_sensitivity_cold_hot_sweets BOOLEAN,
  i_dental_problem_food_collection_between_teeth BOOLEAN,
  i_dental_problem_sensitivity_when_biting BOOLEAN,
  i_dental_problem_grinding_teeth BOOLEAN,
  i_dental_problem_sores_or_growth_in_mouth BOOLEAN,
  dental_history_flossing_frequency VARCHAR(50),
  dental_history_brushing_frequency VARCHAR(50),
  patient_physician VARCHAR(200),
  date_of_last_visit DATE,
  i_fen_phen_yes BOOLEAN,
  i_fen_phen_no BOOLEAN,
  i_serious_illness_or_operations_no BOOLEAN,
  i_serious_illness_or_operations_yes BOOLEAN,
  serious_illness_or_operations_description TEXT,
  i_blood_transfusion_yes BOOLEAN,
  i_blood_transfusion_no BOOLEAN,
  blood_transfusion_approximate_dates VARCHAR(100),
  i_pregnant_no BOOLEAN,
  i_pregnant_yes BOOLEAN,
  i_nursing_yes BOOLEAN,
  i_nursing_no BOOLEAN,
  i_birth_control_yes BOOLEAN,
  i_birth_control_no BOOLEAN,
  i_medical_history_anemia BOOLEAN,
  i_medical_history_fainting BOOLEAN,
  i_medical_history_radiation_treatment BOOLEAN,
  i_medical_history_arthritis_rheumatism BOOLEAN,
  i_medical_history_glaucoma BOOLEAN,
  i_medical_history_respiratory_disease BOOLEAN,
  i_medical_history_artificial_heart_valves BOOLEAN,
  i_medical_history_headaches BOOLEAN,
  i_medical_history_rheumatic_fever BOOLEAN,
  i_medical_history_artificial_joints_pins_etc BOOLEAN,
  i_medical_history_heart_murmur BOOLEAN,
  i_medical_history_scarlet_fever BOOLEAN,
  i_medical_history_asthma BOOLEAN,
  i_medical_history_heart_problems BOOLEAN,
  i_medical_history_sexually_transmitted_disease BOOLEAN,
  i_medical_history_bleeding_abnormally BOOLEAN,
  i_medical_history_hemophilia BOOLEAN,
  i_medical_history_stroke BOOLEAN,
  i_medical_history_blood_disease BOOLEAN,
  i_medical_history_hepatitis BOOLEAN,
  i_medical_history_swelling_of_feet_or_ankles BOOLEAN,
  i_medical_history_cancer BOOLEAN,
  i_medical_history_high_blood_pressure BOOLEAN,
  i_medical_history_thyroid_problems BOOLEAN,
  i_medical_history_chemical_dependency BOOLEAN,
  i_medical_history_hiv_aids BOOLEAN,
  i_medical_history_tobacco_use BOOLEAN,
  i_medical_history_chemotherapy BOOLEAN,
  i_medical_history_jaw_pain BOOLEAN,
  i_medical_history_tonsillitis BOOLEAN,
  i_medical_history_circulatory_problems BOOLEAN,
  i_medical_history_kidney_disease BOOLEAN,
  i_medical_history_tuberculosis BOOLEAN,
  i_medical_history_congenital_heart_lesions BOOLEAN,
  i_medical_history_liver_disease BOOLEAN,
  i_medical_history_ulcer BOOLEAN,
  i_medical_history_diabetes BOOLEAN,
  i_medical_history_mitral_valve_prolapse BOOLEAN,
  i_medical_history_epilepsy BOOLEAN,
  i_medical_history_pacemaker BOOLEAN,
  medication_1 VARCHAR(200),
  diagnosis_1 VARCHAR(200),
  medication_2 VARCHAR(200),
  diagnosis_2 VARCHAR(200),
  medication_3 VARCHAR(200),
  diagnosis_3 VARCHAR(200),
  medication_4 VARCHAR(200),
  diagnosis_4 VARCHAR(200),
  medication_5 VARCHAR(200),
  diagnosis_5 VARCHAR(200),
  medication_6 VARCHAR(200),
  diagnosis_6 VARCHAR(200),
  medication_7 VARCHAR(200),
  diagnosis_7 VARCHAR(200),
  allergy_1 VARCHAR(200),
  allergy_1_2 VARCHAR(200),
  allergy_2 VARCHAR(200),
  allergy_2_2 VARCHAR(200),
  allergy_3 VARCHAR(200),
  allergy_3_2 VARCHAR(200),
  patient_or_guardian_signature_date DATE,
  PRIMARY KEY (patient_name, patient_birthdate)
);

INSERT INTO new_patient_forms VALUES (
  'Justin Thakral', '1990-02-14', '742 Mission St', 'San Francisco', 'CA', 94103, '415-555-0101', '415-555-0102', 'justin.thakral@example.com', true,
  false, false, true, false, false, true, false, 'Thakral Analytics', '510-555-0103', '1200 Broadway',
  'Oakland', 'CA', 94612, 'Maya Thakral', 'Aria Thakral', '408-555-0104', 'Friend Referral', 'Dina Thakral', '1550 Park Ave', 'San Jose',
  'CA', 95113, '408-555-0105', 'dina.thakral@example.com', '1965-09-30', 'Bay Dental Coverage', '916-555-0106', '321-54-9876', 'GRP-77881', 'ID-55882',
  'Sacramento', '250 Capitol Mall', 'CA', 95814, 300, 1100, 1500, 'Justin Thakral', 'Thakral Analytics', '415-555-0107',
  '1 Embarcadero Center', 'San Francisco', 'CA', 94111, 'Pacific Secondary Dental', '213-555-0108', '654-98-3210', 'SEC-33221', 'SEC-99117', '600 W 7th St',
  'Los Angeles', 'CA', 90017, 200, 600, 1200, 'Maya Thakral', 'Thakral Ventures', '619-555-0109', '1221 Broadway',
  'San Diego', 'CA', 92101, 'Chipped molar evaluation', '2024-08-12', '2023-10-05', 'Dr. Elise Carter', '650-555-0110', false, false,
  true, false, false, true, true, true, true, false, 'Weekly', 'Twice Daily',
  'Dr. Priya Shah', '2024-01-22', false, true, false, true, 'Appendectomy 2012', true, false, '2008-06',
  true, false, false, true, false, true, false, false, false, true,
  false, false, false, false, false, false, false, false, true, false,
  false, false, false, false, false, false, false, false, true, false,
  false, false, false, false, false, false, false, false, false, false,
  false, false, true, false, false, false, 'Lisinopril 10mg', 'Hypertension', 'Metformin 500mg', 'Type 2 diabetes',
  'Albuterol inhaler', 'Asthma', 'Ibuprofen 200mg', 'Back pain', 'Atorvastatin 20mg', 'Hyperlipidemia', 'Omeprazole 20mg', 'GERD', 'Sertraline 50mg', 'Anxiety',
  'Penicillin', 'Rash', 'Peanuts', 'Hives', 'Latex', 'Swelling', '2025-01-15'
);
